### ISSUE TITLE
Epub file don't loaded when add dependency & intent?

### ISSUE THREAD

**Issue by Maruf13** [FolioReader/FolioReader-Android#107]
When i donloawd as a zip file, whole "FolioReader-Android" project and put my required epub file in asset folder and call it using openEpub, then it works beautifully.
But when i add dependency to my app build.graddle and call epub file using intent, then my app crashed. I check it many times. but all times it crashed.

**Comment by mahavir155** [comment]
Can you post crash report? Also which version of FolioReader?

**Comment by Maruf13** [comment]
@mahavir155 
FATAL EXCEPTION: main
                                                             
                                                                android.content.ActivityNotFoundException: Unable to find explicit activity class {nextup.stevejobs/com.folioreader.ui.folio.activity.FolioActivity}; have you declared this activity in your AndroidManifest.xml?
                                                                    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1805)
                                                                    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
                                                                    at android.app.Activity.startActivityForResult(Activity.java:4224)
                                                                    at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:54)
                                                                    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
                                                                    at android.app.Activity.startActivityForResult(Activity.java:4183)
                                                                    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:708)
                                                                    at android.app.Activity.startActivity(Activity.java:4507)
                                                                    at android.app.Activity.startActivity(Activity.java:4475)
                                                                    at nextup.stevejobs.MainActivity.openEpub(MainActivity.java:35)
                                                                    at nextup.stevejobs.MainActivity.access$000(MainActivity.java:11)
                                                                    at nextup.stevejobs.MainActivity$1.onClick(MainActivity.java:27)
                                                                    at android.view.View.performClick(View.java:5610)
                                                                    at android.view.View$PerformClick.run(View.java:22265)
                                                                    at android.os.Handler.handleCallback(Handler.java:751)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by mahavir155** [comment]
@Maruf13 add FolioActivity in your projects AndroidManifest:
```
<activity android:name="com.folioreader.ui.folio.activity.FolioActivity">
</activity>

```
Also add following permissions:
```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.INTERNET" />
```
