### ISSUE TITLE
Two Exception

### ISSUE THREAD

**Issue by lsqbeyond** [FolioReader/FolioReader-Android#158]
Hello, I've just met these two mistakes. May I have a problem in the format of my book? But most of my books are, and the problem is a jar. I can't modify it. If I need a book, please send a mailbox lsqbeyond@yeah.net. to solve these two problems. Thanks very much

Shutting down VM
01-03 23:30:32.372 22952-22952/com.folioreader.android.sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.folioreader.android.sample, PID: 22952
                                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{com.folioreader.android.sample/com.folioreader.ui.folio.activity.FolioActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.w3c.dom.Element.getTextContent()' on a null object reference
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2664)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2733)
                                                                                    at android.app.ActivityThread.access$900(ActivityThread.java:187)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                    at android.os.Looper.loop(Looper.java:194)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5877)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)
                                                                                 Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.w3c.dom.Element.getTextContent()' on a null object reference
                                                                                    at org.readium.r2_streamer.parser.OPFParser.parseMainTitle(OPFParser.java:206)
                                                                                    at org.readium.r2_streamer.parser.OPFParser.parseOpfFile(OPFParser.java:50)
                                                                                    at org.readium.r2_streamer.parser.EpubParser.parseEpubFile(EpubParser.java:47)
                                                                                    at org.readium.r2_streamer.server.EpubServer.parse(EpubServer.java:90)
                                                                                    at org.readium.r2_streamer.server.EpubServer.addEpub(EpubServer.java:40)
                                                                                    at com.folioreader.ui.folio.activity.FolioActivity.addEpub(FolioActivity.java:223)
                                                                                    at com.folioreader.ui.folio.activity.FolioActivity.initBook(FolioActivity.java:211)
                                                                                    at com.folioreader.ui.folio.activity.FolioActivity.setupBook(FolioActivity.java:627)
                                                                                    at com.folioreader.ui.folio.activity.FolioActivity.onCreate(FolioActivity.java:161)
                                                                                    at android.app.Activity.performCreate(Activity.java:6127)
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2617)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2733) 
                                                                                    at android.app.ActivityThread.access$900(ActivityThread.java:187) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                    at android.os.Looper.loop(Looper.java:194) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5877) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814) 
 
                                                   Process: com.folioreader.android.sample, PID: 24021
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.folioreader.android.sample/com.folioreader.ui.folio.activity.FolioActivity}: java.lang.NullPointerException: Attempt to read from field 'java.util.List org.readium.r2_streamer.model.publication.EpubPublication.links' on a null object reference
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2664)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2733)
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:187)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584)
                                                       at android.os.Handler.dispatchMessage(Handler.java:111)
                                                       at android.os.Looper.loop(Looper.java:194)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5877)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)
                                                    Caused by: java.lang.NullPointerException: Attempt to read from field 'java.util.List org.readium.r2_streamer.model.publication.EpubPublication.links' on a null object reference
                                                       at org.readium.r2_streamer.server.EpubServer.addLinks(EpubServer.java:68)
                                                       at org.readium.r2_streamer.server.EpubServer.addEpub(EpubServer.java:42)
                                                       at com.folioreader.ui.folio.activity.FolioActivity.addEpub(FolioActivity.java:223)
                                                       at com.folioreader.ui.folio.activity.FolioActivity.initBook(FolioActivity.java:211)
                                                       at com.folioreader.ui.folio.activity.FolioActivity.setupBook(FolioActivity.java:627)
                                                       at com.folioreader.ui.folio.activity.FolioActivity.onCreate(FolioActivity.java:161)
                                                       at android.app.Activity.performCreate(Activity.java:6127)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2617)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2733) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:187) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                       at android.os.Looper.loop(Looper.java:194) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5877) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)

**Comment by mahavir155** [comment]
@lsqbeyond please validate your epubs using validator.idpf.org
Meanwhile, we too are making change to fail gracefully in case of invalid epub.

**Comment by abhi08singh** [comment]
Same issue I am facing. I have already validated the EPUB.
Please resolve this issue ASAP.
