### ISSUE TITLE
Not supporting Epub 

### ISSUE THREAD

**Issue by blennerSilva** [FolioReader/FolioReader-Android#160]
He guys this is my problem:

im getting this log error:

##Log

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.folioreader.android.sample, PID: 17486
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.folioreader.android.sample/com.folioreader.ui.folio.activity.FolioActivity}: java.lang.NullPointerException: Attempt to read from field 'java.util.List org.readium.r2_streamer.model.publication.EpubPublication.links' on a null object reference
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
                      at android.app.ActivityThread.-wrap11(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5443)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                   Caused by: java.lang.NullPointerException: Attempt to read from field 'java.util.List org.readium.r2_streamer.model.publication.EpubPublication.links' on a null object reference
                      at org.readium.r2_streamer.server.EpubServer.addLinks(EpubServer.java:68)
                      at org.readium.r2_streamer.server.EpubServer.addEpub(EpubServer.java:42)
                      at com.folioreader.ui.folio.activity.FolioActivity.addEpub(FolioActivity.java:223)
                      at com.folioreader.ui.folio.activity.FolioActivity.initBook(FolioActivity.java:211)
                      at com.folioreader.ui.folio.activity.FolioActivity.setupBook(FolioActivity.java:623)
                      at com.folioreader.ui.folio.activity.FolioActivity.onCreate(FolioActivity.java:161)
                      at android.app.Activity.performCreate(Activity.java:6245)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:5443) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 

here are the two examples of books that im using : this first one works
<img width="974" alt="screen shot 2018-01-11 at 18 13 24" src="https://user-images.githubusercontent.com/10924301/34845187-26d85f2a-f6fb-11e7-84e6-7a60d6ba9934.png">

this one crashes everytime:

<img width="966" alt="screen shot 2018-01-11 at 18 14 03" src="https://user-images.githubusercontent.com/10924301/34845208-3ca6d8b8-f6fb-11e7-811b-467f8e27823b.png">

as you can se the files are diferent and  i cant launch with this bug can you help me?

**Comment by blennerSilva** [comment]
Updating my issue im getting:
android - org.xml.sax.SAXParseException: Unexpected token (position:TEXT @1:2 in java.io.StringReader@4156ccc8) -

**Comment by mahavir155** [comment]
@blennerSilva Sorry for late reply.. Can you check again on latest version. If still happening, then is it possible for you to PM me ebook on which it is not working?

**Comment by mahavir155** [comment]
Closing due to inactivity
