### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.speech.tts.TextToSpeech.setOnUtteranceCompletedListener()' on a null object reference

### ISSUE THREAD

**Issue by abhi08singh** [FolioReader/FolioReader-Android#162]
Hi, 

Android Version:- 5.1

>java.lang.NullPointerException: Attempt to invoke virtual method 'int android.speech.tts.TextToSpeech.setOnUtteranceCompletedListener(android.speech.tts.TextToSpeech$OnUtteranceCompletedListener)' on a null object reference
                                                                      at com.folioreader.ui.folio.mediaoverlay.MediaController$2.onInit(MediaController.java:113)
                                                                      at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:814)
                                                                      at android.speech.tts.TextToSpeech.initTts(TextToSpeech.java:792)
                                                                      at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:723)
                                                                      at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:702)
                                                                      at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:686)
                                                                      at com.folioreader.ui.folio.mediaoverlay.MediaController.setTextToSpeech(MediaController.java:105)
                                                                      at com.folioreader.ui.folio.fragment.FolioPageFragment.onCreateView(FolioPageFragment.java:180)
                                                                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                                                                      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                                                                      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
                                                                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
                                                                      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
                                                                      at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2209)
                                                                      at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
                                                                      at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:167)
                                                                      at com.folioreader.view.DirectionalViewpager.populate(DirectionalViewpager.java:1326)
                                                                      at com.folioreader.view.DirectionalViewpager.populate(DirectionalViewpager.java:1104)
                                                                      at com.folioreader.view.DirectionalViewpager.setAdapter(DirectionalViewpager.java:500)
                                                                      at com.folioreader.ui.folio.activity.FolioActivity.configFolio(FolioActivity.java:287)
                                                                      at com.folioreader.ui.folio.activity.FolioActivity.onLoadPublication(FolioActivity.java:436)
                                                                      at com.folioreader.ui.folio.presenter.MainPresenter.onReceivePublication(MainPresenter.java:25)
                                                                      at com.folioreader.ui.base.ManifestTask.onPostExecute(ManifestTask.java:68)
                                                                      at com.folioreader.ui.base.ManifestTask.onPostExecute(ManifestTask.java:26)
                                                                      at android.os.AsyncTask.finish(AsyncTask.java:636)
                                                                      at android.os.AsyncTask.access$500(AsyncTask.java:177)
                                                                      at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

In all other Android Version it is running smoothly. Please provide some solution to this ASAP.
Thanks

**Comment by mohammad7hosein** [comment]
> Hi,
> 
> Android Version:- 5.1
> 
> > java.lang.NullPointerException: Attempt to invoke virtual method 'int android.speech.tts.TextToSpeech.setOnUtteranceCompletedListener(android.speech.tts.TextToSpeech$OnUtteranceCompletedListener)' on a null object reference
> > at com.folioreader.ui.folio.mediaoverlay.MediaController$2.onInit(MediaController.java:113)
> > at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:814)
> > at android.speech.tts.TextToSpeech.initTts(TextToSpeech.java:792)
> > at android.speech.tts.TextToSpeech.(TextToSpeech.java:723)
> > at android.speech.tts.TextToSpeech.(TextToSpeech.java:702)
> > at android.speech.tts.TextToSpeech.(TextToSpeech.java:686)
> > at com.folioreader.ui.folio.mediaoverlay.MediaController.setTextToSpeech(MediaController.java:105)
> > at com.folioreader.ui.folio.fragment.FolioPageFragment.onCreateView(FolioPageFragment.java:180)
> > at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
> > at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
> > at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
> > at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
> > at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
> > at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
> > at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
> > at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
> > at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2209)
> > at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
> > at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:167)
> > at com.folioreader.view.DirectionalViewpager.populate(DirectionalViewpager.java:1326)
> > at com.folioreader.view.DirectionalViewpager.populate(DirectionalViewpager.java:1104)
> > at com.folioreader.view.DirectionalViewpager.setAdapter(DirectionalViewpager.java:500)
> > at com.folioreader.ui.folio.activity.FolioActivity.configFolio(FolioActivity.java:287)
> > at com.folioreader.ui.folio.activity.FolioActivity.onLoadPublication(FolioActivity.java:436)
> > at com.folioreader.ui.folio.presenter.MainPresenter.onReceivePublication(MainPresenter.java:25)
> > at com.folioreader.ui.base.ManifestTask.onPostExecute(ManifestTask.java:68)
> > at com.folioreader.ui.base.ManifestTask.onPostExecute(ManifestTask.java:26)
> > at android.os.AsyncTask.finish(AsyncTask.java:636)
> > at android.os.AsyncTask.access$500(AsyncTask.java:177)
> > at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
> > at android.os.Handler.dispatchMessage(Handler.java:102)
> > at android.os.Looper.loop(Looper.java:135)
> > at android.app.ActivityThread.main(ActivityThread.java:5343)
> > at java.lang.reflect.Method.invoke(Native Method)
> > at java.lang.reflect.Method.invoke(Method.java:372)
> > at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
> > at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
> 
> In all other Android Version it is running smoothly. Please provide some solution to this ASAP. Thanks


I have exactly same your error.
how can you solve it?
help me...

**Comment by johnjericmoratas** [comment]
Any updates here?
