### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke virtual method 'fi.iki.elonen.NanoHTTPD$Response fi.iki.elonen.router.RouterNanoHTTPD$UriResource.process on a null object reference

### ISSUE THREAD

**Issue by vikasrairajput** [FolioReader/FolioReader-Android#169]
hey everyone, 

I m getting this type of exception in some of epub files.Please help me out

 E/fi.iki.elonen.NanoHTTPD: Communication with the client broken, or an bug in the handler code
                                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'fi.iki.elonen.NanoHTTPD$Response fi.iki.elonen.router.RouterNanoHTTPD$UriResource.process(java.util.Map, fi.iki.elonen.NanoHTTPD$IHTTPSession)' on a null object reference
                                                                                         at fi.iki.elonen.router.RouterNanoHTTPD$UriRouter.process(RouterNanoHTTPD.java:596)
                                                                                         at fi.iki.elonen.router.RouterNanoHTTPD.serve(RouterNanoHTTPD.java:671)
                                                                                         at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
                                                                                         at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
                                                                                         at java.lang.Thread.run(Thread.java:818)
02-04 21:33:30.182 20868-20922/world.ebook.com.ebookworld E/ManifestTask: ManifestTask failed
                                                                          java.io.IOException: unexpected end of stream on Connection{127.0.0.1:8080, proxy=DIRECT@ hostAddress=127.0.0.1 cipherSuite=none protocol=http/1.1} (recycle count=0)
                                                                              at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:210)
                                                                              at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
                                                                              at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:905)
                                                                              at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:789)
                                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443)
                                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
                                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:231)
                                                                              at com.folioreader.ui.base.ManifestTask.doInBackground(ManifestTask.java:43)
                                                                              at com.folioreader.ui.base.ManifestTask.doInBackground(ManifestTask.java:26)
                                                                              at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                              at java.lang.Thread.run(Thread.java:818)
                                                                           Caused by: java.io.EOFException: \n not found: size=0 content=...
                                                                              at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:200)
                                                                              at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)

**Comment by maloznaal** [comment]
I have same problem, on APIs lower than 24. Have you resolved this issue?

**Comment by HarshaYogesha** [comment]
me also getting same is there any solutions avilable

**Comment by himanshuthakkar2781** [comment]
I am facing the same issue, if any body has found any solution to this, please revert. I guess, it is because of httpurlconnection - as it uses apache...which is now deprecated(in api 23 and below). if this is so, best would be for mahavir155, to replace httpurlconnection with okhttp. I have had to do the same in my project.
