### ISSUE TITLE
App Crashes when reading last page of the ePub

### ISSUE THREAD

**Issue by adeel-quantumcph** [FolioReader/FolioReader-Android#174]
Go to the last page of the ePub and start listing the audio then leave it after a minutes app crashes

Log as follows:

> STACK_TRACE=java.lang.NumberFormatException: For input string: ""
> at java.lang.Integer.parseInt(Integer.java:533)
> at java.lang.Integer.parseInt(Integer.java:556)
> at com.folioreader.ui.folio.fragment.FolioPageFragment$4.onJsAlert(FolioPageFragment.java:551)
> at com.android.webview.chromium.Ap.handleJsAlert(WebViewContentsClientAdapter.java:362)
> at org.chromium.android_webview.AwContentsClientBridge$$Lambda$2.run(Unknown Source)
> at android.os.Handler.handleCallback(Handler.java:751)
> at android.os.Handler.dispatchMessage(Handler.java:95)
> at android.os.Looper.loop(Looper.java:154)
> at android.app.ActivityThread.main(ActivityThread.java:6692)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
> 
> PHONE_MODEL=SM-G935F
> ANDROID_VERSION=7.0

**Comment by adeel-quantumcph** [comment]
Hey guys, can you help me out on this issue   @sameerkhader @mahavir155 @GautamChibde

**Comment by adeel-quantumcph** [comment]
@mahavir155 this issue still exist in the latest version
