### ISSUE TITLE
init BookFailed

### ISSUE THREAD

**Issue by ikhanal** [FolioReader/FolioReader-Android#177]
I have used this library in my app targeting android version 26 and min  15 but I got error while reading epub file from sd card. As I have first downloaded the file from server and read the file from local storage.

` public static void downloadFileFromRemote(Activity activityContext, String url,String fileName)
    {

        File direct = new File(Environment.getExternalStorageDirectory()
                + "/webschool_download");

        if (!direct.exists()) {
            direct.mkdirs();
        }

        DownloadManager mgr = (DownloadManager) activityContext.getSystemService(activityContext.DOWNLOAD_SERVICE);

        Uri downloadUri = Uri.parse(url);
        DownloadManager.Request request = new DownloadManager.Request(
                downloadUri);

        request.setAllowedNetworkTypes(
                DownloadManager.Request.NETWORK_WIFI
                        | DownloadManager.Request.NETWORK_MOBILE)
                .setAllowedOverRoaming(false).setTitle(fileName)
                .setDescription("Dowloading from webschool.")
                .setDestinationInExternalPublicDir("/webschool_download", fileName);

        mgr.enqueue(request);

    }`

And this is how I read
`filePath = new File(path + "/"+ fileName);
            if(filePath.exists() && fileName.contains(".html")|| fileName.contains(".epub")){
                folioReader.openBook(filePath.getAbsolutePath());
            }`
But I got the following exception
`E/FolioActivity: initBook failed
                                                                             java.util.zip.ZipException: File too short to be a zip file: 0
                                                                                 at java.util.zip.ZipFile.<init>(ZipFile.java:208)
                                                                                 at java.util.zip.ZipFile.<init>(ZipFile.java:147)
                                                                                 at java.util.zip.ZipFile.<init>(ZipFile.java:118)
                                                                                 at org.readium.r2_streamer.model.container.EpubContainer.<init>(EpubContainer.java:29)
                                                                                 at com.folioreader.ui.folio.activity.FolioActivity.addEpub(FolioActivity.java:222)
                                                                                 at com.folioreader.ui.folio.activity.FolioActivity.initBook(FolioActivity.java:211)
                                                                                 at com.folioreader.ui.folio.activity.FolioActivity.setupBook(FolioActivity.java:627)
                                                                                 at com.folioreader.ui.folio.activity.FolioActivity.onCreate(FolioActivity.java:161)
                                                                                 at android.app.Activity.performCreate(Activity.java:6675)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2732)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2844)
                                                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                                 at android.os.Looper.loop(Looper.java:203)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6361)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)`

I am unable to sort it out if not possible to solve it I have to roll out this library otherwise.

**Comment by hrishikesh-kadam** [comment]
@ikhanal Can you please check if this issue still occur in v0.4.0?

**Comment by mahavir155** [comment]
No reply.. Closing this issue.. If still reproducible, you can reopen.

**Comment by nerandell** [comment]
This issue is occurring in 0.5.4 as well.
