### ISSUE TITLE
Fatal Exception: java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by khaleeljageer** [FolioReader/FolioReader-Android#184]
`Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at com.folioreader.ui.folio.activity.FolioActivity$1.onClick(FolioActivity.java:171)
       at android.view.View.performClick(View.java:5714)
       at android.view.View$PerformClick.run(View.java:22589)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

sometimes getting this error, while trying to open epub.

**Comment by king3224** [comment]
Hi，excuse me ，I met the same problem today，I want to ask that the problem has been solved？if solved,Can you tell me the solution？

**Comment by hackstarsj** [comment]
Still Not Solved Developer is Not So Active.

**Comment by hackstarsj** [comment]
Try To Rename your filename and make sure that does not have any special character even not space " ".

**Comment by mayank2212** [comment]
Getting this issue very often now. Any solution for this?

**Comment by hackstarsj** [comment]
I modified This Library and Create my own code

**Comment by hrishikesh-kadam** [comment]
@khaleeljageer @king3224 @hackstarsj @mayank2212 Does this error occur still on v0.4.0?
If yes then can you please share EPUB file to reproduce it?

**Comment by hackstarsj** [comment]
New Versions Had also Some issues. sometimes null pointer.
also remember that the file you try to opening doesn't contain white space.

**Comment by hrishikesh-kadam** [comment]
@hackstarsj I just checked again, in v0.4.0 EPUB files with white space and without white space does get open.
Also can you give us log about NPE (Null Pointer Exception)?

**Comment by hackstarsj** [comment]
Sorry But I dont have the new logs.
I modify Your library and complete my works 😊.
Your Library Really Helps me If need i upload your modified library.

**Comment by mayank2212** [comment]
@hrishikesh-kadam here are the logs that i am getting in play console.
java.lang.IndexOutOfBoundsException: 
 
  at java.util.ArrayList.get (ArrayList.java:411)
 
  at com.folioreader.ui.folio.activity.FolioActivity$7.onClick (FolioActivity.java:564)
 
  at android.view.View.performClick (View.java:6312)
 
  at android.view.View$PerformClick.run (View.java:23985)
 
  at android.os.Handler.handleCallback (Handler.java:751)
 
  at android.os.Handler.dispatchMessage (Handler.java:95)
 
  at android.os.Looper.loop (Looper.java:154)
 
  at android.app.ActivityThread.main (ActivityThread.java:6816)
 
  at java.lang.reflect.Method.invoke (Native Method)
 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1563)
 
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1451)

**Comment by hrishikesh-kadam** [comment]
@mayank2212 Which version are you using? And is it stock or have you modified it?

**Comment by Nikhil-z** [comment]
I am also having the same issue @mayank2212  @hrishikesh-kadam. If I am not wrong the new version 0.4.0 also have this issue

**Comment by hrishikesh-kadam** [comment]
@Nikhil-z is it reproducible everytime you open a specific EPUB?

**Comment by Nikhil-z** [comment]
@hrishikesh-kadam  Yes it is possible to reproduce the error but not for every EPUB file. I have found one more interesting fact that the ratio of error generating is higher in a LOWER END device where HIGHER END device hardly gets it while doing MONKEY TESTING. 

`Crashed: main
       at java.util.ArrayList.get(ArrayList.java:411)
       at com.folioreader.ui.folio.activity.FolioActivity$1.onClick(FolioActivity.java:174)
       at android.view.View.performClick(View.java:5612)
       at android.view.View$PerformClick.run(View.java:22288)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

--

Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
       at java.util.ArrayList.get(ArrayList.java:411)
       at com.folioreader.ui.folio.activity.FolioActivity$1.onClick(FolioActivity.java:174)
       at android.view.View.performClick(View.java:5612)
       at android.view.View$PerformClick.run(View.java:22288)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)`

**Comment by hrishikesh-kadam** [comment]
@Nikhil-z Can you please share a specific EPUB in which this issue occurs?
Also the log you listed doesn't seems to be of v0.4.0 - 

`at com.folioreader.ui.folio.activity.FolioActivity$1.onClick(FolioActivity.java:174)` 

There is no click event at that line in `FolioActivity` for v0.4.0 code.

Have you customized the FolioReader?

**Comment by Nikhil-z** [comment]
@hrishikesh-kadam  Yes the log is from 0.3.7 version. I tried v0.4.0 version but which also had same issue. I will share that log too. I have also attached the epub file from which I got the error.
[5ac4def2ef132152285157.epub.zip](https://github.com/FolioReader/FolioReader-Android/files/2212860/5ac4def2ef132152285157.epub.zip)

**Comment by Nikhil-z** [comment]
@hrishikesh-kadam  Here is the crash error log which I found from the v0.4.0

`#0. Crashed: main
       at java.util.ArrayList.get(ArrayList.java:411)
       at com.folioreader.ui.folio.activity.FolioActivity.startContentHighlightActivity(FolioActivity.java:182)
       at com.folioreader.view.FolioToolbar$initListeners$1.onClick(FolioToolbar.kt:50)
       at android.view.View.performClick(View.java:5640)
       at android.view.View$PerformClick.run(View.java:22455)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6165)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

--

Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
       at java.util.ArrayList.get(ArrayList.java:411)
       at com.folioreader.ui.folio.activity.FolioActivity.startContentHighlightActivity(FolioActivity.java:182)
       at com.folioreader.view.FolioToolbar$initListeners$1.onClick(FolioToolbar.kt:50)
       at android.view.View.performClick(View.java:5640)
       at android.view.View$PerformClick.run(View.java:22455)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6165)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
`

**Comment by mahavir155** [comment]
@Nikhil-z Which device and on which android version you reproduced this issue?
Is it reproduced randomly? Or everytime?

Strangely, we didn't able to reproduce here. Other user also facing this issue quite frequently.

**Comment by Nikhil-z** [comment]
@mahavir155  Device was Moto E3 and OS version was Marshmallow. In Lower end device like moto E3 its can be reproduced easily where for higher end device like Mi note 5 its happen randomly

**Comment by hrishikesh-kadam** [comment]
Fixed in v0.4.1

**Comment by hackstarsj** [comment]
Does new version support epub 3 files?

**Comment by mahavir155** [comment]
Previous versions was also supporting epub 3 files.

**Comment by hackstarsj** [comment]
Thanks please wait i while share the file.
