### ISSUE TITLE
Open .epub file from Internal storage

### ISSUE THREAD

**Issue by sirinanjirinsa** [FolioReader/FolioReader-Android#185]
I try
`folioReader = new FolioReader(this);
folioReader.registerHighlightListener(this);
folioReader.openBook(Environment.getExternalStorageDirectory().toString()+"/my_downloads/"+listOfLists.get(position).get(0)+".epub");

getHighlightsAndSave();`
 
Bur not works for me 
I have Error is ...

04-23 14:26:22.515 5603-5603/com.______.______.______ E/FolioActivity: initBook failed
    java.io.FileNotFoundException: File doesn't exist: /my_downloads/152074.epub
        at java.util.zip.ZipFile.<init>(ZipFile.java:212)
        at java.util.zip.ZipFile.<init>(ZipFile.java:148)
        at java.util.zip.ZipFile.<init>(ZipFile.java:119)
        at org.readium.r2_streamer.model.container.EpubContainer.<init>(EpubContainer.java:29)
        at com.folioreader.ui.folio.activity.FolioActivity.addEpub(FolioActivity.java:237)
        at com.folioreader.ui.folio.activity.FolioActivity.initBook(FolioActivity.java:225)
        at com.folioreader.ui.folio.activity.FolioActivity.setupBook(FolioActivity.java:648)
        at com.folioreader.ui.folio.activity.FolioActivity.onCreate(FolioActivity.java:167)
        at android.app.Activity.performCreate(Activity.java:6956) etc.

help me pls, Thank you

**Comment by mahavir155** [comment]
File doesn't exist.. get epub file path properly.. It's not an issue of FolioReader, so closing..
