### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Chomui** [FolioReader/FolioReader-Android#187]
![image](https://user-images.githubusercontent.com/38687271/39178581-c7361538-47ba-11e8-9bbf-3a611986b40d.png)

Doesn't work and crash app
API 16, 27

For example, I took books from the folder Sample/res/raw and Sample/src/main/assets
![image](https://user-images.githubusercontent.com/38687271/39178689-0d25591e-47bb-11e8-8b6f-2bebd79ed101.png)
![image](https://user-images.githubusercontent.com/38687271/39178911-9cd5f398-47bb-11e8-8760-02ad959710eb.png)

**Comment by mahavir155** [comment]
What error it gives?

**Comment by Chomui** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.roman.application2/com.example.roman.application2.BookActivityV2}: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.roman.application2/com.folioreader.ui.folio.activity.FolioActivity}; have you declared this activity in your AndroidManifest.xml?
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2365)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2417)
                      at android.app.ActivityThread.access$600(ActivityThread.java:169)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1377)
                      at android.os.Handler.dispatchMessage(Handler.java:107)
                      at android.os.Looper.loop(Looper.java:194)
                      at android.app.ActivityThread.main(ActivityThread.java:5449)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:525)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.roman.application2/com.folioreader.ui.folio.activity.FolioActivity}; have you declared this activity in your AndroidManifest.xml?
                      at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1689)
                      at android.app.Instrumentation.execStartActivity(Instrumentation.java:1488)
                      at android.app.Activity.startActivityForResult(Activity.java:3401)
                      at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
                      at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
                      at android.app.Activity.startActivityForResult(Activity.java:3357)
                      at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:751)
                      at android.app.Activity.startActivity(Activity.java:3597)
                      at android.app.Activity.startActivity(Activity.java:3565)
                      at com.folioreader.util.FolioReader.openBook(FolioReader.java:75)
                      at com.example.roman.application2.BookActivityV2.onCreate(BookActivityV2.java:24)
                      at android.app.Activity.performCreate(Activity.java:5135)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1146)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2329)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2417) 
                      at android.app.ActivityThread.access$600(ActivityThread.java:169) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1377) 
                      at android.os.Handler.dispatchMessage(Handler.java:107) 
                      at android.os.Looper.loop(Looper.java:194) 
                      at android.app.ActivityThread.main(ActivityThread.java:5449) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:525) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600) 
                      at dalvik.system.NativeStart.main(Native Method)

**Comment by mahavir155** [comment]
You need to declare FolioReaderActivity in your AndroidManifest.xml..
