### ISSUE TITLE
initBook failed

### ISSUE THREAD

**Issue by abhi08singh** [FolioReader/FolioReader-Android#190]
``04-27 14:01:43.270 24223-24223/com.example.app E/FolioActivity: initBook failed
    java.net.BindException: bind failed: EADDRINUSE (Address already in use)
        at libcore.io.IoBridge.bind(IoBridge.java:99)
        at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:139)
        at java.net.ServerSocket.bind(ServerSocket.java:335)
        at java.net.ServerSocket.bind(ServerSocket.java:295)
        at fi.iki.elonen.NanoHTTPD$ServerRunnable.run(NanoHTTPD.java:1761)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: android.system.ErrnoException: bind failed: EADDRINUSE (Address already in use)
        at libcore.io.Posix.bind(Native Method)
        at libcore.io.ForwardingOs.bind(ForwardingOs.java:56)
        at libcore.io.IoBridge.bind(IoBridge.java:97)
        at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:139) 
        at java.net.ServerSocket.bind(ServerSocket.java:335) 
        at java.net.ServerSocket.bind(ServerSocket.java:295) 
        at fi.iki.elonen.NanoHTTPD$ServerRunnable.run(NanoHTTPD.java:1761) 
        at java.lang.Thread.run(Thread.java:818)``

After integrating this in my application i am getting this error.

**Comment by king3224** [comment]
Hi，I met the same problem today，have you solved this problem？if solved，can you tell me the solution？thanks

**Comment by mahavir155** [comment]
@king3224 @abhi08singh All parsing is handle by r2-streamer which uses port number 8080 by default.. If some other process is already using port 8080, then above issue might come..
In that case, you can use different port number by using following method to open book:
`public FolioReader openBook(String assetOrSdcardPath, Config config, int port) `

It will use the port number you provided.

**Comment by king3224** [comment]
oh,I got it.it's right, thanks

**Comment by king3224** [comment]
oh，I got it ，thanks

**Comment by nuwanchamara** [comment]
I tried different port numbers but it not working (In samsung J7) . But it works on ther devices like Xiomi redmi3 , Moto G5 and Huwawi devices (With default port).
