### ISSUE TITLE
SQLiteError when title has apostrophe character

### ISSUE THREAD

**Issue by profdalejuls** [FolioReader/FolioReader-Android#204]
What should I when I encounter this?

`05-11 16:21:01.062 4944-4944/digital.binary.gfslibary E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: digital.binary.gfslibary, PID: 4944
                                                                        android.database.sqlite.SQLiteException: near "s": syntax error (code 1): , while compiling: SELECT rangy FROM highlight_table WHERE pageId = 'The Good Crow's Happy Shop$OEBPS/wrap0000.html'
                                                                        #################################################################
                                                                        Error Code : 1 (SQLITE_ERROR)
                                                                        Caused By : SQL(query) error or missing database.
                                                                        	(near "s": syntax error (code 1): , while compiling: SELECT rangy FROM highlight_table WHERE pageId = 'The Good Crow's Happy Shop$OEBPS/wrap0000.html')
                                                                        #################################################################
                                                                            at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                            at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1095)
                                                                            at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:660)
                                                                            at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                            at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
                                                                            at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                            at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                                            at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1739)
                                                                            at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1678)
                                                                            at com.folioreader.model.sqlite.DbAdapter.getHighlightsForPageId(DbAdapter.java:84)
                                                                            at com.folioreader.model.sqlite.HighLightTable.getHighlightsForPageId(HighLightTable.java:120)
                                                                            at com.folioreader.util.HighlightUtil.generateRangyString(HighlightUtil.java:104)
                                                                            at com.folioreader.ui.folio.fragment.FolioPageFragment$3.onPageFinished(FolioPageFragment.java:438)
                                                                            at com.android.webview.chromium.Ap.onPageFinished(WebViewContentsClientAdapter.java:221)
                                                                            at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:70)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                            at android.os.Looper.loop(Looper.java:164)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6938)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
`

**Comment by hrishikesh-kadam** [comment]
Can you please provide epub file?

**Comment by profdalejuls** [comment]
hrishikesh-kadam unfortunately due to our privacy policy I cannot share you the epub file. You can try renaming an epub and put an apostrophe character in its filename and feed it to the library.

Example filename: `Kadam's ePub Book`
