### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.Curso

### ISSUE THREAD

**Issue by ZayarTun27** [FolioReader/FolioReader-Android#237]
07-08 22:33:29.709 12953-12953/com.manacom.sartittar E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.manacom.sartittar, PID: 12953
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.Cursor android.database.sqlite.SQLiteDatabase.rawQuery(java.lang.String, java.lang.String[])' on a null object reference
        at com.folioreader.model.sqlite.DbAdapter.getHighlightsForPageId(DbAdapter.java:84)
        at com.folioreader.model.sqlite.HighLightTable.getHighlightsForPageId(HighLightTable.java:120)
        at com.folioreader.util.HighlightUtil.generateRangyString(HighlightUtil.java:104)
        at com.folioreader.ui.folio.fragment.FolioPageFragment$3.onPageFinished(FolioPageFragment.java:439)
        at yk.c(PG:236)
        at ako.handleMessage(PG:72)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6684)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by hrishikesh-kadam** [comment]
@ZayarTun27 Unable to reproduce in v0.4.0
Hope you have followed all the steps in Wiki pages.

**Comment by sethchhim** [comment]
@ZayarTun27 @hrishikesh-kadam I am able to recreate this issue. Here are the conditions:

- Epub reader is open with an epub
- App process is killed in the background because other apps need memory (onStop)
- User returns to app (onCreate)
- Crash

```
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.Cursor android.database.sqlite.SQLiteDatabase.rawQuery(java.lang.String, java.lang.String[])' on a null object reference
        at com.folioreader.model.sqlite.DbAdapter.getHighlightsForPageId(DbAdapter.java:84)
        at com.folioreader.model.sqlite.HighLightTable.getHighlightsForPageId(HighLightTable.java:120)
        at com.folioreader.util.HighlightUtil.generateRangyString(HighlightUtil.java:104)
        at com.folioreader.ui.folio.fragment.FolioPageFragment$5.onPageFinished(FolioPageFragment.java:513)
        at xl.c(SourceFile:228)
        at agX.handleMessage(SourceFile:72)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:169)
        at android.app.ActivityThread.main(ActivityThread.java:6578)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```
