### ISSUE TITLE
Images Not showing 

### ISSUE THREAD

**Issue by nuwanchamara** [FolioReader/FolioReader-Android#254]
text content is showing, but images are not showing. My stack trace as bellow

```
8-14 16:46:59.584 24849-24931/com.epub.test.epubtest I/System.out: ResourceHandler Method: GET, Url: /archive/OEBPS/Text/1.jpg
08-14 16:46:59.585 24849-24931/com.epub.test.epubtest E/RouterNanoHTTPD: Error: java.lang.NullPointerException : Attempt to invoke virtual method 'java.lang.String org.readium.r2_streamer.model.publication.link.Link.getTypeLink()' on a null object reference
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.readium.r2_streamer.model.publication.link.Link.getTypeLink()' on a null object reference
        at org.readium.r2_streamer.server.handler.ResourceHandler.get(ResourceHandler.java:79)
        at fi.iki.elonen.router.RouterNanoHTTPD$UriResource.process(RouterNanoHTTPD.java:384)
        at fi.iki.elonen.router.RouterNanoHTTPD$UriRouter.process(RouterNanoHTTPD.java:596)
        at fi.iki.elonen.router.RouterNanoHTTPD.serve(RouterNanoHTTPD.java:671)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Thread.java:761)

```

**Comment by hrishikesh-kadam** [comment]
@nuwanchamara Can you please share EPUB file for further investigation?
