### ISSUE TITLE
Failed resolution of: Lorg/readium/r2_streamer/server/EpubServerSingleton

### ISSUE THREAD

**Issue by stevensiahaan** [FolioReader/FolioReader-Android#278]
Issue / Feature -  Failed resolution of: Lorg/readium/r2_streamer/server/EpubServerSingleton
FolioReader version -  0.4.3
FolioReader Stock / Modified -  
Android SDK - 
Mobile / Tablet / Emulator Info -  Mobile OPPO Android a37f
Crash / Error - NoClassDefFoundError

Steps to reproduce / Describe in detail - 
 FATAL EXCEPTION: main
                                                                      Process: id.android.baboo.dev, PID: 32341
                                                                      java.lang.NoClassDefFoundError: Failed resolution of: Lorg/readium/r2_streamer/server/EpubServerSingleton;
                                                                          at com.folioreader.ui.folio.activity.FolioActivity.initBook(FolioActivity.java:446)
                                                                          at com.folioreader.ui.folio.activity.FolioActivity.setupBook(FolioActivity.java:943)
                                                                          at com.folioreader.ui.folio.activity.FolioActivity.onCreate(FolioActivity.java:270)
                                                                          at android.app.Activity.performCreate(Activity.java:6093)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2458)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
                                                                          at android.app.ActivityThread.access$1000(ActivityThread.java:164)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:160)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5541)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
                                                                       Caused by: java.lang.ClassNotFoundException: Didn't find class "org.readium.r2_streamer.server.EpubServerSingleton" on path: DexPathList[[zip file "/data/app/id.android.steven.dev-2/base.apk"],nativeLibraryDirectories=[/data/app/id.android.steven.dev-2/lib/arm, /vendor/lib, /system/lib]]
                                                                          at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                          at com.folioreader.ui.folio.activity.FolioActivity.initBook(FolioActivity.java:446) 
                                                                          at com.folioreader.ui.folio.activity.FolioActivity.setupBook(FolioActivity.java:943) 
                                                                          at com.folioreader.ui.folio.activity.FolioActivity.onCreate(FolioActivity.java:270) 
                                                                          at android.app.Activity.performCreate(Activity.java:6093) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2458) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577) 
                                                                          at android.app.ActivityThread.access$1000(ActivityThread.java:164) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:160) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5541) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
                                                                      	Suppressed: java.lang.ClassNotFoundException: org.readium.r2_streamer.server.EpubServerSingleton
                                                                          at java.lang.Class.classForName(Native Method)
                                                                          at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                          at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                          		... 17 more
                                                                       Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by stevensiahaan** [comment]
@hebertialmeida
