### ISSUE TITLE
Crash While opening this book

### ISSUE THREAD

**Issue by miladmetias13** [FolioReader/FolioReader-Android#298]
Issue / Feature -  Issue
FolioReader version -  com.folioreader:folioreader:0.5.1
FolioReader Stock / Modified -  Stock
Android SDK - 28
Mobile / Tablet / Emulator Info -  Mobile Samsung Note 4
Crash / Error - Crash

Steps to reproduce / Describe in detail - open the attached book then try to swipe horizontal

open the .epub file after extracting he .zip file
[22.zip](https://github.com/FolioReader/FolioReader-Android/files/2482657/22.zip)

**Comment by miladmetias13** [comment]
10-16 15:39:10.907 18341-20736/com.konooz E/ResourceHandler: kotlin.KotlinNullPointerException
    kotlin.KotlinNullPointerException
        at org.readium.r2.streamer.server.handler.ResourceHandler.get(ResourceHandler.kt:67)
        at org.nanohttpd.router.RouterNanoHTTPD$UriResource.process(RouterNanoHTTPD.java:385)
        at org.nanohttpd.router.RouterNanoHTTPD$UriRouter.process(RouterNanoHTTPD.java:597)
        at org.nanohttpd.router.RouterNanoHTTPD.serve(RouterNanoHTTPD.java:672)
        at org.nanohttpd.protocols.http.NanoHTTPD$1.handle(NanoHTTPD.java:376)
        at org.nanohttpd.protocols.http.NanoHTTPD$1.handle(NanoHTTPD.java:372)
        at org.nanohttpd.protocols.http.NanoHTTPD.handle(NanoHTTPD.java:535)
        at org.nanohttpd.protocols.http.HTTPSession.execute(HTTPSession.java:421)
        at org.nanohttpd.protocols.http.ClientHandler.run(ClientHandler.java:75)
        at java.lang.Thread.run(Thread.java:818)
10-16 15:39:10.912 18341-18594/com.konooz D/mali_winsys: new_window_surface returns 0x3000,  [1440x2560]-format:1
10-16 15:39:10.922 18341-20751/com.konooz E/HtmlTask: HtmlTask failed
    java.io.FileNotFoundException: http://127.0.0.1:8080/22/OEBPS/Text/%D8%A7%D9%84%D9%85%D8%A7%D8%B6%D9%8A%20%D9%88%D8%A7%D9%84%D9%85%D8%B3%D8%AA%D9%82%D8%A8%D9%84.html
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:242)
        at com.folioreader.ui.base.HtmlTask.doInBackground(HtmlTask.java:38)
        at com.folioreader.ui.base.HtmlTask.doInBackground(HtmlTask.java:22)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)


10-16 15:39:11.802 18341-20818/com.konooz E/ResourceHandler: kotlin.KotlinNullPointerException
    kotlin.KotlinNullPointerException
        at org.readium.r2.streamer.server.handler.ResourceHandler.get(ResourceHandler.kt:67)
        at org.nanohttpd.router.RouterNanoHTTPD$UriResource.process(RouterNanoHTTPD.java:385)
        at org.nanohttpd.router.RouterNanoHTTPD$UriRouter.process(RouterNanoHTTPD.java:597)
        at org.nanohttpd.router.RouterNanoHTTPD.serve(RouterNanoHTTPD.java:672)
        at org.nanohttpd.protocols.http.NanoHTTPD$1.handle(NanoHTTPD.java:376)
        at org.nanohttpd.protocols.http.NanoHTTPD$1.handle(NanoHTTPD.java:372)
        at org.nanohttpd.protocols.http.NanoHTTPD.handle(NanoHTTPD.java:535)
        at org.nanohttpd.protocols.http.HTTPSession.execute(HTTPSession.java:421)
        at org.nanohttpd.protocols.http.ClientHandler.run(ClientHandler.java:75)
        at java.lang.Thread.run(Thread.java:818)

**Comment by miladmetias13** [comment]
many thanks to you , 

i really can't thank you enough

wish you the best
