### ISSUE TITLE
Permission denied to epub file

### ISSUE THREAD

**Issue by AsyaLeah** [FolioReader/FolioReader-Android#305]
Hi, Could you please take a look at this issue :)

Issue / Feature - 
FolioReader version -  0.5.1
FolioReader Stock / Modified -  
Android SDK - Android Studio 
Mobile / Tablet / Emulator Info -  Emulator Api 28
Crash / Error - 
2018-11-22 14:18:49.291 325-325/com.folioreader.android.sample E/Error: Could not generate container
    java.io.FileNotFoundException: /storage/emulated/0/folioreader/TheSilverChair/TheSilverChair.epub (Permission denied)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:238)
        at java.util.zip.ZipFile.<init>(ZipFile.java:152)
        at java.util.zip.ZipFile.<init>(ZipFile.java:123)
        at org.readium.r2.streamer.container.ContainerEpub.<init>(ContainerEpub.kt:48)
        at org.readium.r2.streamer.parser.EpubParser.generateContainerFrom(EpubParser.kt:52)
        at org.readium.r2.streamer.parser.EpubParser.parse(EpubParser.kt:73)
        at com.folioreader.ui.folio.activity.FolioActivity.initBook(FolioActivity.java:458)
        at com.folioreader.ui.folio.activity.FolioActivity.setupBook(FolioActivity.java:432)
        at com.folioreader.ui.folio.activity.FolioActivity.onRequestPermissionsResult(FolioActivity.java:973)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7608)
        at android.app.Activity.dispatchActivityResult(Activity.java:7458)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4353)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4402)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2018-11-22 14:18:49.333 325-325/com.folioreader.android.sample E/FolioActivity: -> Failed to initialize book
    java.lang.NullPointerException: Attempt to invoke virtual method 'org.readium.r2.shared.Publication org.readium.r2.streamer.parser.PubBox.getPublication()' on a null object reference
        at com.folioreader.ui.folio.activity.FolioActivity.initBook(FolioActivity.java:469)
        at com.folioreader.ui.folio.activity.FolioActivity.setupBook(FolioActivity.java:432)
        at com.folioreader.ui.folio.activity.FolioActivity.onRequestPermissionsResult(FolioActivity.java:973)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7608)
        at android.app.Activity.dispatchActivityResult(Activity.java:7458)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4353)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4402)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
So, Unable to display my epub file

Steps to reproduce / Describe in detail - 
This happens when you first start the application after installation.
If you close and reopen the application - everything works

**Comment by hrishikesh-kadam** [comment]
@AsyaLeah Unable to reproducible this issue.
Is this happening with all EPUBs or just specific EPUB?

**Comment by AsyaLeah** [comment]
This Is happening with all EPUBs

**Comment by muhammedakiftas** [comment]
i have the same problem. 

java.io.FileNotFoundException: /storage/emulated/0/folioreader/TheSilverChair/TheSilverChair.epub (Permission denied)

SOLVED : 


<manifest ... >
<application **android:requestLegacyExternalStorage="true"** ... >
...
</application>
</manifest>
