### ISSUE TITLE
App crashes when opening a book

### ISSUE THREAD

**Issue by YadhuIleaf** [FolioReader/FolioReader-Android#312]
Error details:
java.util.zip.ZipException: Not a zip archive
        at java.util.zip.ZipFile.readCentralDir(ZipFile.java:397)
        at java.util.zip.ZipFile.<init>(ZipFile.java:175)
        at java.util.zip.ZipFile.<init>(ZipFile.java:142)
        at org.readium.r2.streamer.container.ContainerEpub.<init>(ContainerEpub.kt:48)
        at org.readium.r2.streamer.parser.EpubParser.generateContainerFrom(EpubParser.kt:52)
        at org.readium.r2.streamer.parser.EpubParser.parse(EpubParser.kt:73)
        at com.folioreader.ui.folio.activity.FolioActivity.initBook(FolioActivity.java:458)
        at com.folioreader.ui.folio.activity.FolioActivity.setupBook(FolioActivity.java:432)
        at com.folioreader.ui.folio.activity.FolioActivity.onCreate(FolioActivity.java:283)
        at android.app.Activity.performCreate(Activity.java:6358)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2438)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2545)
        at android.app.ActivityThread.access$1100(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1396)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5602)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
12-12 14:58:58.854 22578-22578/com.shulph.shulph E/FolioActivity: -> Failed to initialize book
    java.lang.NullPointerException: Attempt to invoke virtual method 'org.readium.r2.shared.Publication org.readium.r2.streamer.parser.PubBox.getPublication()' on a null object reference
        at com.folioreader.ui.folio.activity.FolioActivity.initBook(FolioActivity.java:469)
        at com.folioreader.ui.folio.activity.FolioActivity.setupBook(FolioActivity.java:432)
        at com.folioreader.ui.folio.activity.FolioActivity.onCreate(FolioActivity.java:283)
        at android.app.Activity.performCreate(Activity.java:6358)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2438)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2545)
        at android.app.ActivityThread.access$1100(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1396)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5602)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
12-12 14:59:01.062 826-959/? E/XTCC-5.1.0.9: [PosMgr] handlePosition failed: 12
12-12 14:59:02.239 22799-22915/? E/SntpClient: request time failed: java.net.SocketTimeoutException
12-12 14:59:02.916 22578-22578/com.shulph.shulph E/CrashlyticsCore: Failed to execute task.
    java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:177)
        at com.crashlytics.android.core.CrashlyticsBackgroundWorker.submitAndWait(CrashlyticsBackgroundWorker.java:41)
        at com.crashlytics.android.core.CrashlyticsController.handleUncaughtException(CrashlyticsController.java:320)
        at com.crashlytics.android.core.CrashlyticsController$6.onUncaughtException(CrashlyticsController.java:300)
        at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:42)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
12-12 14:59:02.917 22578-22578/com.shulph.shulph E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.shulph.shulph, PID: 22578
    java.lang.NullPointerException: Attempt to invoke interface method 'android.graphics.drawable.Drawable android.view.MenuItem.getIcon()' on a null object reference
        at com.folioreader.ui.folio.activity.FolioActivity.onCreateOptionsMenu(FolioActivity.java:356)
        at android.app.Activity.onCreatePanelMenu(Activity.java:2951)
        at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:378)
        at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at android.support.v7.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2549)
        at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
        at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
        at android.os.Handler.handleCallback(Handler.java:742)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5602)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)

**Comment by YadhuIleaf** [comment]
We have been using older Folio Reader so far. We decided to upgrade recently and getting this error after that

**Comment by hrishikesh-kadam** [comment]
@YadhuIleaf You seems to be working on Shulp project.
It would have been helpful if you could fill the Issue template like these - https://github.com/FolioReader/FolioReader-Android/blob/master/.github/Issue_Template_Examples.md

Can you share EPUB file with us for further investigation?

**Comment by YadhuIleaf** [comment]
Can you share your email ?.

**Comment by YadhuIleaf** [comment]
@hrishikesh-kadam This is how we initialise Folio for opening an epub file:
FolioReader.get()
                .setReadPositionListener(thisFragment)
                .setReadPosition(readPosition)
                .setConfig(config, true)
                .openBook(bookPath, String.valueOf(book.bookId));
where bookPath is the sd card path of the file

**Comment by YadhuIleaf** [comment]
line 458: FolioActivity: pubBox = epubParser.parse(path, "");  epubParser couoldn't initialise pubBox.
path = "/data/data/com.shulph.shulph/files/9781787432680.epub".

**Comment by hrishikesh-kadam** [comment]
@YadhuIleaf I am able to open the book you provided without any error.
I did open through assets folder and even through /data/data/{app_package}/files/{epub} way.

Unable to produce the issue on Stock version 0.5.1

**Comment by YadhuIleaf** [comment]
Oh okey . We have cross checked the implementation and when we debugged it seemed like EpubParser(Epub Container) was causing it. It would be helpful if you can help me with it. It works well with older version

**Comment by hrishikesh-kadam** [comment]
How are you importing your modified FolioReader in Shulp?
Is it just by storing .aar in lib folder or by publishing locally and then importing through gradle?

**Comment by YadhuIleaf** [comment]
Initially we were just copying it in to the lib. But now we changed it using mavenLocal() after consulting Mahaveer

**Comment by YadhuIleaf** [comment]
Anyway we will check it again from start .
