### ISSUE TITLE
Unable to open Epub Assets in this Demo

### ISSUE THREAD

**Issue by jayesh28589** [FolioReader/FolioReader-Android#319]
Hello hrishikesh,

I have downloaded this whole project in integrate in android studio.

when I run the app sample, and click on "OPEN EPUB ASSETS" then no file display.

I checked Log and it is showing.

> 2018-12-19 09:02:40.416 8048-8048/com.folioreader.android.sample E/FolioActivity: -> Failed to initialize book
    java.net.BindException: Address already in use
        at java.net.PlainSocketImpl.socketBind(Native Method)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.bind(ServerSocket.java:377)
        at java.net.ServerSocket.bind(ServerSocket.java:331)
        at org.nanohttpd.protocols.http.ServerRunnable.run(ServerRunnable.java:63)
        at java.lang.Thread.run(Thread.java:761)

Then I click on Menu Item at top-left , it is showing contents then I click on chapter II, application become crash.

I test this on Motorola X play with Android 7.1.1 version.
Please fix this and update this code.

Crash Log.

> 2018-12-19 09:07:45.184 8048-8048/com.folioreader.android.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.folioreader.android.sample, PID: 8048
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=77, result=-1, data=Intent { (has extras) }} to activity {com.folioreader.android.sample/com.folioreader.ui.folio.activity.FolioActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4130)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4173)
        at android.app.ActivityThread.-wrap20(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6165)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
        at com.folioreader.ui.folio.activity.FolioActivity.goToChapter(FolioActivity.java:713)
        at com.folioreader.ui.folio.activity.FolioActivity.onActivityResult(FolioActivity.java:758)
        at android.app.Activity.dispatchActivityResult(Activity.java:6946)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4126)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4173) 
        at android.app.ActivityThread.-wrap20(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6165) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778) 

Thanks

**Comment by hrishikesh-kadam** [comment]
@jayesh28589 This has been fixed in https://github.com/codetoart/FolioReader-Android/commit/c285fc53fb9ac895e31796d9b351a37ace8a208a which will get released in next release.

Till then try to close any other instances of app running FolioReader and close any local server runing on localhost:8080. Or you can choose other port number using FolioReader#openBook(String assetOrSdcardPath, int port)

**Comment by hrishikesh-kadam** [comment]
Do read commit message in above commit.
