### ISSUE TITLE
[IMP][Crash]is there any way to handle errors in FolioAtivity

### ISSUE THREAD

**Issue by anuragvarshney** [FolioReader/FolioReader-Android#327]
Is there any way to handle errors in FolioActivity, My case is when any invalid path is provide to FolioActivity, the activity is opened but after clicking the hamburger icon on the left the app crahses.

Issue / Feature - Issue
FolioReader version -  0.5.1
FolioReader Stock / Modified -  stock
Android SDK - 28
Mobile / Tablet / Emulator Info -  mobile
Crash / Error - java.lang.NullPointerException: Attempt to invoke virtual method 'org.readium.r2.shared.Publication org.readium.r2.streamer.parser.PubBox.getPublication()' on a null object reference
        at com.folioreader.ui.folio.activity.FolioActivity.startContentHighlightActivity(FolioActivity.java:406)
        at com.folioreader.ui.folio.activity.FolioActivity.onOptionsItemSelected(FolioActivity.java:374)
        at android.app.Activity.onMenuItemSelected(Activity.java:3208)
        at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:436)
        at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:196)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at android.support.v7.widget.ToolbarWidgetWrapper$1.onClick(ToolbarWidgetWrapper.java:188)
        at android.view.View.performClick(View.java:5612)
        at android.view.View$PerformClick.run(View.java:22285)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

Steps to reproduce / Describe in detail - give an invalid file path in Folioreader.openBookMethod, and click on hamburger icon on the left

**Comment by anuragvarshney** [comment]
Can you provide some sort of error handler that if any error occurs in parsing or getting the epub file we can gracefully handle that error because as of now the app crashes

**Comment by anuragvarshney** [comment]
Guys, can someone help me out here?
