### ISSUE TITLE
Unable to open my ebooks. Please help me as soon as possible

### ISSUE THREAD

**Issue by nikhilwork** [FolioReader/FolioReader-Android#328]
Issue / Feature - Unable to open my ebooks. Please help me as soon as possible
[DemoEpub.zip](https://github.com/FolioReader/FolioReader-Android/files/2716563/DemoEpub.zip)

FolioReader version -   implementation "com.folioreader:folioreader:0.5.1"
FolioReader Stock / Modified -  Stock
Android SDK - 28
Mobile / Tablet / Emulator Info -  Mobile
Crash / Error - Unable to open my epub, but its working fine in epub readers but not working in folio reader. Can you please check the attached epub file?

Steps to reproduce / Describe in detail -

**Comment by nikhilwork** [comment]
12-29 22:32:26.467 29115-29115/com.niit.engagetc E/Error: Missing File : META-INF/container.xml
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.util.zip.ZipEntry.getName()' on a null object reference
        at java.util.zip.ZipFile.getInputStream(ZipFile.java:288)
        at org.readium.r2.streamer.container.ZipArchiveContainer$DefaultImpls.data(ZipArchiveContainer.kt:32)
        at org.readium.r2.streamer.container.ContainerEpub.data(ContainerEpub.kt:22)
        at org.readium.r2.streamer.parser.EpubParser.parse(EpubParser.kt:79)
        at com.folioreader.ui.folio.activity.FolioActivity.initBook(FolioActivity.java:458)
        at com.folioreader.ui.folio.activity.FolioActivity.setupBook(FolioActivity.java:432)
        at com.folioreader.ui.folio.activity.FolioActivity.onCreate(FolioActivity.java:283)
        at android.app.Activity.performCreate(Activity.java:6112)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1117)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2609)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2721)
        at android.app.ActivityThread.access$900(ActivityThread.java:168)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5753)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
12-29 22:32:26.487 29115-29115/com.niit.engagetc E/FolioActivity: -> Failed to initialize book
    java.lang.NullPointerException: Attempt to invoke virtual method 'org.readium.r2.shared.Publication org.readium.r2.streamer.parser.PubBox.getPublication()' on a null object reference
        at com.folioreader.ui.folio.activity.FolioActivity.initBook(FolioActivity.java:469)
        at com.folioreader.ui.folio.activity.FolioActivity.setupBook(FolioActivity.java:432)
        at com.folioreader.ui.folio.activity.FolioActivity.onCreate(FolioActivity.java:283)
        at android.app.Activity.performCreate(Activity.java:6112)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1117)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2609)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2721)
        at android.app.ActivityThread.access$900(ActivityThread.java:168)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5753)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
