### ISSUE TITLE
Crash when opened epub assets using Folio Reader sample app

### ISSUE THREAD

**Issue by iLeafSolutionsPvtLtd** [FolioReader/FolioReader-Android#341]
Issue / Feature - Crash in your sample app
FolioReader version -  0.5.4
FolioReader Stock / Modified -  stock
Android SDK - 
Mobile / Tablet / Emulator Info -  
Crash / Error - 

java.lang.RuntimeException: Unable to destroy activity {com.folioreader.android.sample/com.folioreader.ui.activity.FolioActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter lastReadLocator
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3943)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3961)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4165)
        at android.app.ActivityThread.access$1200(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1404)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5602)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
     Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter lastReadLocator
        at com.folioreader.ui.activity.FolioActivity.storeLastReadLocator(FolioActivity.kt)
        at com.folioreader.ui.fragment.FolioPageFragment.onDestroy(FolioPageFragment.kt:842)
        at androidx.fragment.app.Fragment.performDestroy(Fragment.java:2699)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1591)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at androidx.fragment.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3260)
        at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:274)
        at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:419)
        at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:210)
        at com.folioreader.ui.activity.FolioActivity.onDestroy(FolioActivity.kt:831)
        at android.app.Activity.performDestroy(Activity.java:6529)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1143)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3930)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3961) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4165) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1404) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:157) 
        at android.app.ActivityThread.main(ActivityThread.java:5602) 
        at java.lang.reflect.Method.invoke(Native Method) 

Steps to reproduce / Describe in detail - Run your Folio sample app, open epub assets try changing fonts you will get this crash

**Comment by OlegTarashkevich** [comment]
Hi guys @hrishikesh-kadam @mahavir155 !
I have the same issue, the app crashes after device rotation.

**Comment by HariMohan-eng** [comment]
Hello,
in iOS folio reader kit have issue, when play sound the book is not showing white screen will appear on ios 13. but when we run in ios 12 or below its working fine. please fix issue for ios 13 ASAP.

**Comment by HariMohan-eng** [comment]
I need on urgent basis, i have used in big project.
