### ISSUE TITLE
0.5.3 & 0.5.4 both crashes when changing configuration

### ISSUE THREAD

**Issue by iLeafSolutionsPvtLtd** [FolioReader/FolioReader-Android#342]
Issue / Feature - App crashes when we tried to adjust configuration(font, day/night mode etc). The issue is noticed in your sample app provided. 

FolioReader version -  0.5.3 & 0.54
FolioReader Stock / Modified -  stock
Android SDK - 27
Mobile / Tablet / Emulator Info -  mobile
Crash / Error - 
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.folioreader.android.sample, PID: 5240
    kotlin.KotlinNullPointerException
        at com.folioreader.ui.fragment.FolioPageFragment$webViewClient$1.onPageFinished(FolioPageFragment.kt:431)
        at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:546)
        at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:201)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5602)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)

Steps to reproduce / Describe in detail - open a book using your sample app provided. try adjusting configurations

**Comment by iLeafSolutionsPvtLtd** [comment]
Kindly let us know if this is going to be fixed. I am not sure if you people are able to produce the same . But it needs an immediate attention as we postponed the latest release of our app for a stable version of Folio Reader.

**Comment by ashokkumar88** [comment]
@iLeafSolutionsPvtLtd Did you find any work around? It is happening in Android 9 for me.

**Comment by iLeafSolutionsPvtLtd** [comment]
No...we are using the older version of FolioReader now.
