### ISSUE TITLE
App crashing while click's on search Button.

### ISSUE THREAD

**Issue by kaushalandy** [FolioReader/FolioReader-Android#345]
2019-01-29 12:47:20.571 2120-2120/com.folioreader.android.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.folioreader.android.sample, PID: 2120
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.folioreader.android.sample/com.folioreader.ui.activity.SearchActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class android.support.v7.widget.Toolbar
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2861)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
     Caused by: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class android.support.v7.widget.Toolbar
     Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class android.support.v7.widget.Toolbar
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.widget.Toolbar" on path: DexPathList[[zip file "/data/app/com.folioreader.android.sample-by9U0eBSaepSSqn1FmE0QQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.folioreader.android.sample-by9U0eBSaepSSqn1FmE0QQ==/lib/arm, /data/app/com.folioreader.android.sample-by9U0eBSaepSSqn1FmE0QQ==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.view.LayoutInflater.createView(LayoutInflater.java:606)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.folioreader.ui.activity.SearchActivity.onCreate(SearchActivity.kt:107)
        at android.app.Activity.performCreate(Activity.java:7032)
        at android.app.Activity.performCreate(Activity.java:7023)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1236)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2814)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

**Comment by BharathRaoSS** [comment]
same issue here

**Comment by onuraykut** [comment]
Make you sure you don't have a any SearchActivtiy class in your own package.This is solved my same problem.

**Comment by kaushalandy** [comment]
Same here 😁

**Comment by hrishikesh-kadam** [comment]
Thanks @onuraykut for the solution.

**Comment by BharathRaoSS** [comment]
I tried renaming the SearchActivity of my Project to Other name. Still the crash issue is there when I click on Search icon of epub reader. Tried various way (cache invalidate restart, removing and adding the sdk),etc

**Comment by kaushalandy** [comment]
@BharathRaoSS  Please do check XML file also, may be you have activity_search.xml in your app too.
Remane that aswell

**Comment by BharathRaoSS** [comment]
Thank you so much @kaushalandy . This helped me a lot
