### ISSUE TITLE
menu.findItem(R.id.itemSearch) must not be null

### ISSUE THREAD

**Issue by dhinx** [FolioReader/FolioReader-Android#346]
Issue / Feature - **When call method openBook with file from assets**
FolioReader version -  **0.5.4**
FolioReader Stock / Modified -  **Stock**
Android SDK - **21**
Mobile / Tablet / Emulator Info -  **Xiaomi Mi 8 Lite And Emulator Android Pie 9.0**
Crash / Error - `java.lang.IllegalStateException: menu.findItem(R.id.itemSearch) must not be null`

Steps to reproduce / Describe in detail - 

> 2019-01-29 17:37:56.621 20162-20162/com.example.securepdf E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.securepdf, PID: 20162
    java.lang.IllegalStateException: menu.findItem(R.id.itemSearch) must not be null
        at com.folioreader.ui.activity.FolioActivity.onCreateOptionsMenu(FolioActivity.kt:365)
        at android.app.Activity.onCreatePanelMenu(Activity.java:3466)
        at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:313)
        at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2549)
        at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
        at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:173)
        at android.app.ActivityThread.main(ActivityThread.java:6653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)

**Comment by Shruti7032** [comment]
Delete your app menu_main xml. It is overriding folio's menu_main xml. that's why the crash is happening.
