### ISSUE TITLE
Crashes on clicking search

### ISSUE THREAD

**Issue by himanshuthakkar2781** [FolioReader/FolioReader-Android#360]
Issue / Feature - 
FolioReader version -  5.4
FolioReader Stock / Modified -  
Android SDK - 
Mobile / Tablet / Emulator Info - Moto g play  
Crash / Error - b.t: null cannot be cast to non-null type com.folioreader.ui.view.FolioSearchView
        at com.folioreader.ui.activity.SearchActivity.onCreateOptionsMenu(SearchActivity.kt:226)
[crashes when search.txt](https://github.com/FolioReader/FolioReader-Android/files/2988309/crashes.when.search.txt)

Steps to reproduce / Describe in detail -

**Comment by himanshuthakkar2781** [comment]
2019-03-22 16:38:30.473 30586-30586/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.gurumaa.amritvarsha, PID: 30586
    java.lang.IllegalArgumentException: Parameter specified as non-null is null: method b.e.b.j.b, parameter href
        at org.readium.r2.a.i.<init>(Locator.kt)
        at com.folioreader.b.c.c.<init>(SearchLocator.kt:24)
        at com.folioreader.d.a.a(SearchViewModel.kt:198)
        at com.folioreader.d.a.a(SearchViewModel.kt:166)
        at com.folioreader.d.a.a(SearchViewModel.kt:17)
        at com.folioreader.d.a$b.a(SearchViewModel.kt:80)
        at e.h$a$1$1.run(ExecutorCallAdapterFactory.java:71)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6165)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
2019-03-22 16:38:34.856 22304-32734/? E/GeofenceHelper: Failed: remove geofences by PendingIntent
2019-03-22 16:38:35.093 22304-22304/? E/FirebaseInstanceId: Failed to resolve target intent service, skipping classname enforcement
2019-03-22 16:38:35.094 22304-22304/? E/FirebaseInstanceId: Error while delivering the message: ServiceIntent not found.
2019-03-22 16:38:35.100 3228-14708/? E/WakeLock: GCMSEND release without a matched acquire!
2019-03-22 16:38:49.400 2430-13677/? E/ActivityManager: applyOptionsLocked: Unknown animationType=0
2019-03-22 16:38:49.434 2430-2922/? E/ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ LISTEN id=2441, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND] ]
2019-03-22 16:38:49.435 2430-2896/? E/Sensors: AccSensor::setDelay  handle:1 delay:66
2019-03-22 16:38:49.435 2430-2896/? E/Sensors: AccSensor::setDelay finished!!!
2019-03-22 16:38:49.436 2430-2922/? E/ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ LISTEN id=2442, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND] ]
2019-03-22 16:38:51.017 736-810/? E/libEGL: validate_display:99 error 3008 (EGL_BAD_DISPLAY)
2019-03-22 16:38:52.782 736-736/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.gurumaa.amritvarsha, PID: 736
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.Cursor android.database.sqlite.SQLiteDatabase.rawQuery(java.lang.String, java.lang.String[])' on a null object reference
        at com.folioreader.b.e.a.a(DbAdapter.java:84)
        at com.folioreader.b.e.c.c(HighLightTable.java:115)
        at com.folioreader.util.c.a(HighlightUtil.java:102)
        at com.folioreader.ui.c.b$i.onPageFinished(FolioPageFragment.kt:416)
        at xH.c(SourceFile:222)
        at ayK.handleMessage(SourceFile:72)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6165)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
2019-03-22 16:38:54.333 347-376/? E/BufferQueueProducer: [com.gurumaa.amritvarsha/com.folioreader.ui.activity.FolioActivity] dequeueBuffer: BufferQueue has been abandoned
2019-03-22 16:38:54.468 2430-3278/? E/ActivityManager: Found activity ActivityRecord{c8439bf u0 com.gurumaa.amritvarsha/com.folioreader.ui.activity.FolioActivity t48092 f} in proc activity list using null instead of expected ProcessRecord{ed5725b 736:com.gurumaa.amritvarsha/u0a481}
2019-03-22 16:38:54.577 2430-2922/? E/ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ LISTEN id=2447, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND] ]
2019-03-22 16:38:54.578 2430-2922/? E/ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ LISTEN id=2446, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND] ]
2019-03-22 16:38:55.175 22304-321/? E/GmsContextObserver: Received context data while not listening
2019-03-22 16:38:55.204 2430-13680/? E/Sensors: AccSensor::setDelay  handle:1 delay:20
2019-03-22 16:38:55.204 2430-13680/? E/Sensors: AccSensor::setDelay finished!!!
2019-03-22 16:38:55.355 862-862/? E/BluetoothVendorJni: register_com_android_bluetooth_btservice_vendor:
2019-03-22 16:38:55.371 862-862/? E/BluetoothVendorJni: register_com_android_bluetooth_btservice_vendor:
2019-03-22 16:38:55.425 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Below are the guidelines/instructions for editing this database file.
2019-03-22 16:38:55.425 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Note 1: User should turn of the BT, before updating this database file.
2019-03-22 16:38:55.425 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Note 2: Maximum length of the line should not be more than 1023 characters.
2019-03-22 16:38:55.425 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Note 3: Line started with the # is treated as comments.
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Note 4: Comment lines in between the entries are not allowed.
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Note 5: All duplicated entries including main BL types will be ignored.
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #1. Below are the four tags for blacklist
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #   A. Address_Based   C. Manufacturer_based
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #   B. Name_Based      D. Vndr_Prdt_Based
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #   E. SSR_Max_Lat_Based
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section ##
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #   A. Address_Based :  This tag refers to Address based blacklist
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #   Input Type       :   Input value should be only 3 to 6 bytes of BD address
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #   Format Type      :   Address should be in XX:XX:XX format
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #   Examples         :   00:01:03 = Address_Based
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section ###
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #   B. Name_Based :   This tag refers to Name based blacklist.
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #   Input type    :   Input should be only string and length of the string
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #                     should not be more than 248 characters.
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #   Format Type   :   string
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #   Examples      :   Sample Headset name = Name_Based
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section ####
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #   C. Manufacturer_Based :  This tag refers to Manufacturer based blacklist
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #   Input type  : Input should be in Hexadecimal Number of Manufacturer
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #   Format Type : 2 Bytes Hexadecimal Value
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #   Examples    : 0X0023 = Manufacturer_Based
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #####
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #   D. Vndr_Prdt_Based : This tag refers to vendor and product based blacklist
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #   Input type  : Input should be in Hexadecimal value
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #   Format Type : 4 bytes hex value( 2bytes of vendor  and 2 bytes of product),
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #                 Vendor and product hex values should be separated with delimiter(-).
2019-03-22 16:38:55.426 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #   Examples    : 0X00AB-0X00BC = Vndr_Prdt_Based
2019-03-22 16:38:55.427 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #   E. SSR_Max_Lat_Based : This tag refers to SSR Max LAtency based blacklist
2019-03-22 16:38:55.427 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #   Input type  : Input value should be combination of first 3 bytes of BD address and
2019-03-22 16:38:55.427 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #                 Hexadecimal value of SSR Max Latency
2019-03-22 16:38:55.427 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #   Format Type : Address should be in XX:XX:XX format followed by 2 bytes hex value
2019-03-22 16:38:55.427 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #                 of max latency Address and Max Latency should be separated with delimiter(-).
2019-03-22 16:38:55.427 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #   Examples    : 00:01:03-0X00AB = SSR_Max_Lat_Based
2019-03-22 16:38:55.427 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # ******************************* Start of Blacklist Database ********************************
2019-03-22 16:38:55.427 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #Disable secure connections
2019-03-22 16:38:55.427 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #This is for pre BT 4.1/2 devices that do not handle secure mode very well.
2019-03-22 16:38:55.428 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Some devices have proven problematic during the pairing process, often
2019-03-22 16:38:55.428 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # requiring multiple retries to complete pairing. To avoid degrading the user
2019-03-22 16:38:55.428 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # experience for those devices, automatically re-try pairing if page
2019-03-22 16:38:55.428 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # timeouts are received during pairing.
2019-03-22 16:38:55.428 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Devices requiring this workaround do not handle Bluetooth Absolute Volume
2019-03-22 16:38:55.428 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # control correctly, leading to undesirable (potentially harmful) volume levels
2019-03-22 16:38:55.428 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # or general lack of controlability.
2019-03-22 16:38:55.429 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Disable automatic pairing with headsets/car-kits
2019-03-22 16:38:55.429 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Some car kits do not react kindly to a failed pairing attempt and
2019-03-22 16:38:55.429 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # do not allow immediate re-pairing. Blacklist these so that the initial
2019-03-22 16:38:55.429 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # pairing attempt makes it to the user instead
2019-03-22 16:38:55.429 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Use a fixed pin for specific keyboards
2019-03-22 16:38:55.429 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Keyboards should use a variable pin at all times. However, some keyboards
2019-03-22 16:38:55.429 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # require a fixed pin of all 0000. This workaround enables auto pairing for
2019-03-22 16:38:55.429 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # those keyboards.
2019-03-22 16:38:55.430 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Some headsets have audio jitter issues because of increased re-transmissions as the
2019-03-22 16:38:55.430 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # 3 Mbps packets have a lower link margin, and are more prone to interference. We can
2019-03-22 16:38:55.430 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # disable 3DH packets (use only 2DH packets) for the ACL link to improve sensitivity
2019-03-22 16:38:55.430 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # when streaming A2DP audio to the headset. Air sniffer logs show reduced
2019-03-22 16:38:55.430 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # re-transmissions after switching to 2DH packets.
2019-03-22 16:38:55.430 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Disable 3Mbps packets and use only 2Mbps packets for ACL links when streaming audio.
2019-03-22 16:38:55.430 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Some HID devices have proven problematic behaviour if SDP is initiated again
2019-03-22 16:38:55.430 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # while HID connection is in progress or if more than 1 SDP connection is created
2019-03-22 16:38:55.430 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # with those HID devices rsulting in issues of connection failure with such devices.
2019-03-22 16:38:55.430 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # To avoid degrading the user experience with those devices, SDP is not attempted
2019-03-22 16:38:55.430 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # as part of pairing process.
2019-03-22 16:38:55.431 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Some HID pointing devices have proven problematic behaviour if pairing is initiated with
2019-03-22 16:38:55.431 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # them, resulting in no response for authentication request and ultimately resulting
2019-03-22 16:38:55.431 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # in connection failure.
2019-03-22 16:38:55.431 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # To avoid degrading the user experience with those devices, authentication request
2019-03-22 16:38:55.431 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # is not requested explictly.
2019-03-22 16:38:55.431 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # HID Keyboards that claim support for multitouch functionality have issue with
2019-03-22 16:38:55.431 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # normal functioning of keyboard because of issues in USB HID kernel driver.
2019-03-22 16:38:55.431 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # To avoid degrading the user experience with those devices, digitizer record
2019-03-22 16:38:55.431 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # is removed from the report descriptor.
2019-03-22 16:38:55.431 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Some HID devices have problematic behaviour where when hid link is in Sniff
2019-03-22 16:38:55.431 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # and DUT is in Slave role for SCO link ( not eSCO) any solution cannot maintain
2019-03-22 16:38:55.431 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # the link as  SCO scheduling over a short period will overlap with Sniff link due to
2019-03-22 16:38:55.431 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # slave drift.
2019-03-22 16:38:55.431 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # To avoid degrading the user experience with those devices, sniff is disabled from
2019-03-22 16:38:55.431 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # link policy when sco is active, and enabled when sco is disabled.
2019-03-22 16:38:55.431 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Few carkits take long time to start sending AT commands
2019-03-22 16:38:55.431 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Increase AG_CONN TIMEOUT so that AG connection go through
2019-03-22 16:38:55.431 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Some HOGP devices do not respond well when we switch from default LE conn parameters
2019-03-22 16:38:55.431 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # to preferred conn params immediately post connection. Disable automatic switching to
2019-03-22 16:38:55.432 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # preferred conn params for such devices and allow them to explicity ask for it.
2019-03-22 16:38:55.432 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Few remote devices do not understand AVRCP version greater than 1.3. For these
2019-03-22 16:38:55.432 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # devices, we would like to blacklist them and advertise AVRCP version as 1.3
2019-03-22 16:38:55.432 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Fallback to AVRCP version 1.4 for remote to initiate browse connection
2019-03-22 16:38:55.432 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Disable role switch for headsets/car-kits
2019-03-22 16:38:55.432 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Some car kits allow role switch but when DUT initiates role switch
2019-03-22 16:38:55.432 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Remote will go to bad state and its leads to LMP time out.
2019-03-22 16:38:55.433 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Disable role switch policy for headsets/car-kits
2019-03-22 16:38:55.433 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Some car kits initiate a role switch but won't initiate encryption
2019-03-22 16:38:55.433 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # after role switch complete
2019-03-22 16:38:55.433 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # certain remote A2DP sinks have issue playing back Music in AAC format.
2019-03-22 16:38:55.433 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # disable AAC for those headsets so that it switch to SBC
2019-03-22 16:38:55.433 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # 1. byte alignment issues with encoder (solo3::20:3c:ae,airpods::4c:32:75)
2019-03-22 16:38:55.433 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # 2. remote sending 128 instead of 128k as bitrate (cadillac::28:a1:83,buick_verona::ac:7a:4d,maruti_brezzai:28:a1:83)
2019-03-22 16:38:55.433 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # 3. remote flowing off for media packets (parrotzik_2.0/Honda2k17::A0:14:3D,Tesla_s::90:03:b7)
2019-03-22 16:38:55.434 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Devices requiring this workaround do not handle Bluetooth PBAP 1.2
2019-03-22 16:38:55.434 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # version correctly, leading them to go in bad state. So for better
2019-03-22 16:38:55.434 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # interoperability respond with PBAP 1.1 as supported version.
2019-03-22 16:38:55.434 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Honor remote avdtp start, certain carkits send avdt_start along with avrcp
2019-03-22 16:38:55.434 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # passthrough cmd. If DUT suspends remote start and initiate avdtp start, remote
2019-03-22 16:38:55.434 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # suspends DUT's start request. So honor remote start for certain devices.
2019-03-22 16:38:55.434 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # Devices requiring this workaround do not handle SSR max latency values as mentioned,
2019-03-22 16:38:55.434 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # in their SDP HID Record properly and lead to connection timeout or lags. To prevent
2019-03-22 16:38:55.434 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # such scenarios, device requiring this workaorund need to use specific ssr max latency
2019-03-22 16:38:55.434 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section # values.
2019-03-22 16:38:55.434 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #Some device reports support for hf indicator, but it's HFP version as 1.5. The
2019-03-22 16:38:55.434 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #behaviour violates spec and shall cause problem when DUT support HFP1.7, thus
2019-03-22 16:38:55.434 862-877/? E/bt_device_interop:  Invalid Section, ignoring the section #blacklisting such devices and remove remote's hf indicator bit if not support HFP1.7.
2019-03-22 16:38:55.442 862-862/? E/bt_btif_vendor: init
2019-03-22 16:38:55.471 862-877/? E/bt_vnd_log: init_vnd_Logger, Logger Not enabled from config file
2019-03-22 16:38:55.475 862-877/? E/bt_vendor: get_bt_soc_type: Failed to get soc type
2019-03-22 16:38:55.561 862-888/? E/bt_btm: btm_ble_multi_adv_init: max adv instances: 10
2019-03-22 16:38:55.576 862-882/? E/BluetoothRemoteDevices: devicePropertyChangedCallback: bdDevice: 30:A9:DE:75:07:62, value is empty for type: 10
2019-03-22 16:38:55.584 862-882/? E/BluetoothRemoteDevices: devicePropertyChangedCallback: bdDevice: FC:62:B9:C4:FC:AC, value is empty for type: 10
2019-03-22 16:38:55.588 862-882/? E/BluetoothRemoteDevices: devicePropertyChangedCallback: bdDevice: 74:95:EC:70:2D:A7, value is empty for type: 10
2019-03-22 16:38:55.705 2430-3200/? E/IzatSvc_ComboNetworkProvider: E/Exiting with error virtual void izat_manager::ComboNetworkProvider::reportLocationMsg::proc() const line 187 "1"
2019-03-22 16:38:55.732 22304-321/? E/GmsContextObserver: Received context data while not listening
2019-03-22 16:38:55.744 2430-13672/? E/Sensors: AccSensor::setDelay  handle:1 delay:66
2019-03-22 16:38:55.744 2430-13672/? E/Sensors: AccSensor::setDelay finished!!!
2019-03-22 16:38:55.831 2430-13673/? E/Sensors: AccSensor::setDelay  handle:1 delay:20
2019-03-22 16:38:55.832 2430-13673/? E/Sensors: AccSensor::setDelay finished!!!
2019-03-22 16:38:55.847 22304-321/? E/GmsContextObserver: Received context data while not listening
2019-03-22 16:38:59.296 2430-2907/? E/Sensors: AccSensor::setDelay  handle:1 delay:66
2019-03-22 16:38:59.296 2430-2907/? E/Sensors: AccSensor::setDelay finished!!!
2019-03-22 16:39:04.339 2430-2450/? E/Sensors: AccSensor::setDelay  handle:1 delay:20
2019-03-22 16:39:04.339 2430-2450/? E/Sensors: AccSensor::setDelay finished!!!
2019-03-22 16:39:05.021 407-2653/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'UID' not found
2019-03-22 16:39:07.798 2430-13670/? E/Sensors: AccSensor::setDelay  handle:1 delay:66
2019-03-22 16:39:07.798 2430-13670/? E/Sensors: AccSensor::setDelay finished!!!
2019-03-22 16:39:09.796 407-2653/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'UID' not found
2019-03-22 16:39:12.843 2430-3924/? E/Sensors: AccSensor::setDelay  handle:1 delay:20
2019-03-22 16:39:12.843 2430-3924/? E/Sensors: AccSensor::setDelay finished!!!
2019-03-22 16:39:16.320 2430-13678/? E/Sensors: AccSensor::setDelay  handle:1 delay:66
2019-03-22 16:39:16.321 2430-13678/? E/Sensors: AccSensor::setDelay finished!!!
2019-03-22 16:39:20.179 22304-32734/? E/GeofenceHelper: Failed: remove geofences by PendingIntent
2019-03-22 16:39:20.389 22304-22304/? E/FirebaseInstanceId: Failed to resolve target intent service, skipping classname enforcement
2019-03-22 16:39:20.390 22304-22304/? E/FirebaseInstanceId: Error while delivering the message: ServiceIntent not found.
2019-03-22 16:39:20.393 3228-14708/? E/WakeLock: GCMSEND release without a matched acquire!
2019-03-22 16:39:21.342 2430-13674/? E/Sensors: AccSensor::setDelay  handle:1 delay:20
2019-03-22 16:39:21.343 2430-13674/? E/Sensors: AccSensor::setDelay finished!!!
2019-03-22 16:39:24.757 2430-2450/? E/Sensors: AccSensor::setDelay  handle:1 delay:66
2019-03-22 16:39:24.757 2430-2450/? E/Sensors: AccSensor::setDelay finished!!!
2019-03-22 16:39:24.828 22304-860/? E/GmsContextObserver: Received context data while not listening
2019-03-22 16:39:36.194 407-2653/? E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'UID' not found

**Comment by KishanViramgama** [comment]
#345 check this @himanshuthakkar2781

**Comment by himanshuthakkar2781** [comment]
Thanks for the reply. I have already checked #345. I Do not have SearchActivity in my project. Have also checked my project for XML file activity_search.xml. I do not have that either. 
This is my proguard file below
-------------------------------------------------------
-ignorewarnings
#-keep class * { public private *; }

# Bottom Navigation Helper
-keep class android.support.design.internal.BottomNavigationItemView{ *; }
-keep class android.support.design.internal.BottomNavigationMenuView{ *; }

-keep class android.support.v4.app.** { *; }
-keep interface android.support.v4.app.** { *; }
-keep class com.actionbarsherlock.** { *; }
-keep interface com.actionbarsherlock.** { *; }
#-keep class com.jfrog.bintray.** { *; }
#-keep class com.folioreader.** { *; }
#-keep class com.github.dcendents.** { *; }
#-keep class org.jetbrains.** { *; }




-keep class com.shockwave.**
#-keep class com.ubook** { *; }
#-keep class com.search** { *; }
#-keep class com.menu** { *; }




-keepattributes *Annotation*
-keepclassmembers class ** {
    @org.greenrobot.eventbus.Subscribe <methods>;
}
-keep enum org.greenrobot.eventbus.ThreadMode { *; }
-dontwarn nl.siegmann.epublib.**
 -------------------------------------------------------------------

Step 1 - If I use the proguard file as above, app crashes immediately on clicking search.
Step 2 - If I uncomment the commented lines above, the app does not crash though, but the search result shows NULL.
It would be great if u could help...

**Comment by KishanViramgama** [comment]
i am using this proguard-rules.pro

**#Event Bus**
-keepattributes *Annotation*
-keepclassmembers class * {
    @org.greenrobot.eventbus.Subscribe <methods>;
}
-keep enum org.greenrobot.eventbus.ThreadMode { *; }

# Only required if you use AsyncExecutor
-keepclassmembers class * extends org.greenrobot.eventbus.util.ThrowableFailureEvent {
    <init>(java.lang.Throwable);
}

**i am using this search class android.support.v7.widget.SearchView**

-keep class android.support.v7.widget.SearchView { *; }
 this not work then try this
-keep class android.support.v7.widget.** { *; }

**Comment by himanshuthakkar2781** [comment]
Tried the proguard rules mentioned above - 
Still get the following error below---

2019-03-23 20:37:06.890 21119-21119/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.gurumaa.amritvarsha, PID: 21119
    b.t: null cannot be cast to non-null type com.folioreader.ui.view.FolioSearchView
        at com.folioreader.ui.activity.SearchActivity.onCreateOptionsMenu(SearchActivity.kt:226)
        at android.app.Activity.onCreatePanelMenu(Activity.java:3146)
        at androidx.f.a.e.onCreatePanelMenu(FragmentActivity.java:378)
        at androidx.appcompat.view.i.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at androidx.appcompat.app.h$d.onCreatePanelMenu(AppCompatDelegateImpl.java:2549)
        at androidx.appcompat.view.i.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at androidx.appcompat.app.l.l(ToolbarActionBar.java:455)
        at androidx.appcompat.app.l$1.run(ToolbarActionBar.java:56)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6165)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

**Comment by nobodysfault** [comment]
`-keep class com.folioreader.ui.view.FolioSearchView { *; }` or 
`-keep public class * extends androidx.appcompat.widget.SearchView { *; }` 
should do the trick
