### ISSUE TITLE
Context is Null

### ISSUE THREAD

**Issue by mackongo** [FolioReader/FolioReader-Android#367]
FolioReader folioReader = FolioReader.get();

Always returns null and it crash.

Any work around?

Issue / Feature - 
FolioReader version -  
FolioReader Stock / Modified -  
Android SDK - 
Mobile / Tablet / Emulator Info -  
Crash / Error - 

Steps to reproduce / Describe in detail -

**Comment by mahavir155** [comment]
@mackongo from where you calling FolioReader.get(). Can you share some piece of code?

**Comment by CrescentMedia** [comment]
Same problem here!!!

2021-07-31 17:15:30.861 10864-10864/com.sako.test E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sako.test, PID: 10864
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sako.test/com.sako.test.MainActivity}: java.lang.IllegalStateException: -> context == null
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.IllegalStateException: -> context == null
        at com.folioreader.FolioReader.get(FolioReader.java:107)
        at com.sako.test.MainActivity.onCreate(MainActivity.kt:41)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
