### ISSUE TITLE
Failed to initialize book

### ISSUE THREAD

**Issue by khaleeljageer** [FolioReader/FolioReader-Android#369]
Issue / Feature - Issue
FolioReader version -  0.5.4
FolioReader Stock / Modified -  Stock
Android SDK - 28
Mobile / Tablet / Emulator Info -  Mobile
Crash / Error - 
`2019-04-23 18:31:57.527 4407-4407/com.jskaleel.fte V/FolioActivity: -> initDistractionFreeMode
2019-04-23 18:31:57.537 4407-4407/com.jskaleel.fte V/FolioActivity: -> hideSystemUI
2019-04-23 18:31:57.537 4407-4407/com.jskaleel.fte V/FolioActivity: -> showSystemUI
2019-04-23 18:31:57.619 4407-4407/com.jskaleel.fte V/FolioActivity: -> setDayMode
2019-04-23 18:31:57.621 4407-4407/com.jskaleel.fte V/FolioActivity: -> initMediaController
2019-04-23 18:31:57.627 4407-4407/com.jskaleel.fte V/FolioActivity: -> setupBook
2019-04-23 18:31:57.627 4407-4407/com.jskaleel.fte V/FolioActivity: -> initBook
2019-04-23 18:31:57.645 4407-4407/com.jskaleel.fte E/Error: Could not generate container
    java.lang.Exception: Missing File
        at org.readium.r2.streamer.parser.EpubParser.generateContainerFrom(EpubParser.kt:52)
        at org.readium.r2.streamer.parser.EpubParser.parse(EpubParser.kt:71)
        at com.folioreader.ui.activity.FolioActivity.initBook(FolioActivity.kt:477)
        at com.folioreader.ui.activity.FolioActivity.setupBook(FolioActivity.kt:447)
        at com.folioreader.ui.activity.FolioActivity.onCreate(FolioActivity.kt:296)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1293)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3101)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3260)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1976)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6912)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
2019-04-23 18:31:57.647 4407-4407/com.jskaleel.fte D/AppUtil: -> getAvailablePortNumber -> portNumber 8080 available
2019-04-23 18:31:57.658 4407-4407/com.jskaleel.fte E/FolioActivity: -> Failed to initialize book
    kotlin.KotlinNullPointerException
        at com.folioreader.ui.activity.FolioActivity.initBook(FolioActivity.kt:493)
        at com.folioreader.ui.activity.FolioActivity.setupBook(FolioActivity.kt:447)
        at com.folioreader.ui.activity.FolioActivity.onCreate(FolioActivity.kt:296)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1293)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3101)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3260)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1976)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6912)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
2019-04-23 18:31:57.666 4407-4407/com.jskaleel.fte V/FolioActivity: -> onPostCreate
2019-04-23 18:31:57.667 4407-4407/com.jskaleel.fte V/FolioActivity: -> onResume
2019-04-23 18:31:57.691 4407-4407/com.jskaleel.fte V/FolioAppBarLayout: -> onApplyWindowInsets
2019-04-23 18:31:57.800 4407-4407/com.jskaleel.fte V/FolioActivity: -> onSystemUiVisibilityChange -> visibility = 0
2019-04-23 18:31:57.800 4407-4407/com.jskaleel.fte V/FolioActivity: -> distractionFreeMode = false
`

Steps to reproduce / Describe in detail - 
My entire project migrated to androidx and using compile sdk 28. Increased folioreader version to 0.5.4 previously I used 0.4.1. When I open the file saved inside app directory, getting this error.

**Comment by mahavir155** [comment]
> V/FolioActivity: -> initBook 2019-04-23 18:31:57.645 4407-4407/com.jskaleel.fte E/Error: Could not generate container java.lang.Exception: Missing File at 

@khaleeljageer It occurs when the path you provided is incorrect. Closing this issue.
