### ISSUE TITLE
Can't read some books.

### ISSUE THREAD

**Issue by jskcse4** [FolioReader/FolioReader-Android#38]
Im using this library to read ebooks from my app. Recently I found that I can't read some books. Getting following error in Log.

`FATAL EXCEPTION: main
                                                                Process: com.jskaleel.fte, PID: 2165
                                                                java.lang.IllegalArgumentException: META-INF is not a constant in com.folioreader.util.AppUtil$FileType
                                                                    at java.lang.Enum.valueOf(Enum.java:200)
                                                                    at com.folioreader.util.AppUtil$FileType.valueOf(AppUtil.java:77)
                                                                    at com.folioreader.util.AppUtil.getTypeOfOPF(AppUtil.java:502)
                                                                    at com.folioreader.util.AppUtil.getPathOPF(AppUtil.java:441)
                                                                    at com.folioreader.activity.FolioActivity.readHTmlString(FolioActivity.java:434)
                                                                    at com.folioreader.activity.FolioActivity.getChapterHtmlContent(FolioActivity.java:413)
                                                                    at com.folioreader.fragments.FolioPageFragment.initWebView(FolioPageFragment.java:172)
                                                                    at com.folioreader.fragments.FolioPageFragment.onCreateView(FolioPageFragment.java:152)
                                                                    at android.support.v4.app.Fragment.performCreateView(Fragment.java:2087)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
                                                                    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                                                    at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1643)
                                                                    at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:679)
                                                                    at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
                                                                    at com.folioreader.view.DirectionalViewpager.populate(DirectionalViewpager.java:1332)
                                                                    at com.folioreader.view.DirectionalViewpager.populate(DirectionalViewpager.java:1113)
                                                                    at com.folioreader.view.DirectionalViewpager.setAdapter(DirectionalViewpager.java:521)
                                                                    at com.folioreader.activity.FolioActivity.configFolio(FolioActivity.java:356)
                                                                    at com.folioreader.activity.FolioActivity.loadBook(FolioActivity.java:171)
                                                                    at com.folioreader.activity.FolioActivity.access$700(FolioActivity.java:65)
                                                                    at com.folioreader.activity.FolioActivity$3$1.run(FolioActivity.java:161)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:234)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5526)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

Please help to fix out this.

**Comment by jskcse4** [comment]
More Info : 

I can read the same book in FBReader, PageTurner apps. Getting only error on this Library.

**Comment by mahavir-jain** [comment]
Is it possible to share github project where you are using this ebook? Or probably just share ebook which is not working?

**Comment by pablo384** [comment]
Try paste this into your buildgradle module app. Down of buildTypes.


packagingOptions {         
exclude 'META-INF/ASL2.0'         
exclude 'META-INF/DEPENDENCIES.txt'        
 exclude 'META-INF/LICENSE.txt'         
exclude 'META-INF/NOTICE.txt'         
exclude 'META-INF/NOTICE'         
exclude 'META-INF/LICENSE'         
exclude 'META-INF/DEPENDENCIES'         
exclude 'META-INF/notice.txt'         
exclude 'META-INF/license.txt'         
exclude 'META-INF/dependencies.txt'         
exclude 'META-INF/LGPL2.1'        
 exclude 'META-INF/services/javax.annotation.processing.Processor'     
}

**Comment by jskcse4** [comment]
@pablo384 its not working

**Comment by jskcse4** [comment]
@mahavir-jain here is the which i can read & can't read. (both the books are Tamil Ebooks).
Can't Read :
1. [Ayesha](https://drive.google.com/file/d/0B7j3fgGSw9Wca0JVd09VSV9qNmc/view?usp=sharing)

Can Read :
2. [Vizha Eduthupar](https://drive.google.com/file/d/0B7j3fgGSw9WcaHdVRm95NFMtUmc/view?usp=sharing)

**Comment by jskcse4** [comment]
Please take a look [here](https://github.com/FolioReader/FolioReader-Android/pull/40)

**Comment by mahavir-jain** [comment]
fixed in v0.2.3
