### ISSUE TITLE
Book open with error some book. After loading can show only white display

### ISSUE THREAD

**Issue by sereja93** [FolioReader/FolioReader-Android#394]
Issue / Feature - Issue
FolioReader version -  0.5.4
FolioReader Stock / Modified -  Style modified
Android SDK - 29
Mobile / Tablet / Emulator Info -  All version
Crash / Error - Error

Select book/ Show error

```
 Caused by: java.io.EOFException: \n not found: size=0 content=...
        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:200)
        at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
        at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127) 
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737) 
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244) ```
[Mojenkov_V._Gen_Direktora_17_Pravil_P(1).epub.zip](https://github.com/FolioReader/FolioReader-Android/files/3613054/Mojenkov_V._Gen_Direktora_17_Pravil_P.1.epub.zip)

**Comment by sereja93** [comment]
problem solved after replace dot symbols in file name.

**Comment by syedecryptr** [comment]
> problem solved after replace dot symbols in file name.

Thanks a lot, you are a lifesaver cannot thank you enough for the solution I was struggling with the same issue for days.
