### ISSUE TITLE
Crash: Couldn't resolve menu item onClick handler goBackButtonClicked in class com.folioreader.ui.activity.FolioActivity

### ISSUE THREAD

**Issue by jaysson** [FolioReader/FolioReader-Android#409]
Issue / Feature - Opening Epub
FolioReader version -  0.5.4
FolioReader Stock / Modified -  Stock
Android SDK - 8.1.0
Mobile / Tablet / Emulator Info -  Moto G5 S+, and almost every device tested
Crash / Error - 
```
E/AndroidRuntime(13501): android.view.InflateException: Couldn't resolve menu item onClick handler goBackButtonClicked in class com.folioreader.ui.activity.FolioActivity
E/AndroidRuntime(13501): 	at androidx.appcompat.view.SupportMenuInflater$InflatedOnMenuItemClickListener.<init>(SupportMenuInflater.java:254)
E/AndroidRuntime(13501): 	at androidx.appcompat.view.SupportMenuInflater$MenuState.setItem(SupportMenuInflater.java:482)
E/AndroidRuntime(13501): 	at androidx.appcompat.view.SupportMenuInflater$MenuState.addItem(SupportMenuInflater.java:530)
E/AndroidRuntime(13501): 	at androidx.appcompat.view.SupportMenuInflater.parseMenu(SupportMenuInflater.java:206)
E/AndroidRuntime(13501): 	at androidx.appcompat.view.SupportMenuInflater.inflate(SupportMenuInflater.java:128)
E/AndroidRuntime(13501): 	at com.folioreader.ui.activity.FolioActivity.onCreateOptionsMenu(FolioActivity.kt:362)
E/AndroidRuntime(13501): 	at android.app.Activity.onCreatePanelMenu(Activity.java:3407)
E/AndroidRuntime(13501): 	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:325)
E/AndroidRuntime(13501): 	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
E/AndroidRuntime(13501): 	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2549)
E/AndroidRuntime(13501): 	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
E/AndroidRuntime(13501): 	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
E/AndroidRuntime(13501): 	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
E/AndroidRuntime(13501): 	at android.os.Handler.handleCallback(Handler.java:790)
E/AndroidRuntime(13501): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(13501): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(13501): 	at android.app.ActivityThread.main(ActivityThread.java:6626)
E/AndroidRuntime(13501): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13501): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/AndroidRuntime(13501): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
E/AndroidRuntime(13501): Caused by: java.lang.NoSuchMethodException: goBackButtonClicked [interface android.view.MenuItem]
E/AndroidRuntime(13501): 	at java.lang.Class.getMethod(Class.java:2068)
E/AndroidRuntime(13501): 	at java.lang.Class.getMethod(Class.java:1690)
E/AndroidRuntime(13501): 	at androidx.appcompat.view.SupportMenuInflater$InflatedOnMenuItemClickListener.<init>(SupportMenuInflater.java:250)
E/AndroidRuntime(13501): 	... 19 more
Lost connection to device.
```

Steps to reproduce / Describe in detail - Call the following:
```kt
val folioReader = FolioReader.get().setConfig(Config().setDirection(Config.Direction.HORIZONTAL).setShowTts(false).setFont(3), true)
folioReader.openBook(path)
```

**Comment by adityajoshi12** [comment]
is this issue is resolved? I am also facing same issue.

**Comment by marcqtan** [comment]
same here

**Comment by jaded0** [comment]
This issue is still happening, almost a year later
