### ISSUE TITLE
Crash on Android 10 when trying to open a book

### ISSUE THREAD

**Issue by dr-Fade** [FolioReader/FolioReader-Android#464]
Issue / Feature - Issue
FolioReader version - 0.5.4
FolioReader Stock / Modified - Stock
Android SDK - 29
Mobile / Tablet / Emulator Info - emulator + tablet
Crash / Error - Crash

Steps to reproduce / Describe in detail - 
1. Install the reader app.
2. Pass a file to it,
3. App crashed with an error:
```
2020-07-14 14:56:33.207 7353-7353/test.app E/Error: Could not generate container
    java.io.FileNotFoundException: /storage/emulated/0/Download/book.epub (Permission denied)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:265)
        at java.util.zip.ZipFile.<init>(ZipFile.java:187)
        at java.util.zip.ZipFile.<init>(ZipFile.java:158)
        at org.readium.r2.streamer.container.ContainerEpub.<init>(ContainerEpub.kt:56)
        at org.readium.r2.streamer.parser.EpubParser.generateContainerFrom(EpubParser.kt:55)
        at org.readium.r2.streamer.parser.EpubParser.parse(EpubParser.kt:71)
        at com.folioreader.ui.activity.FolioActivity.initBook(FolioActivity.kt:477)
        at com.folioreader.ui.activity.FolioActivity.setupBook(FolioActivity.kt:447)
        at com.folioreader.ui.activity.FolioActivity.onCreate(FolioActivity.kt:296)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
Adding <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/> and granting it using the `adb shell pm grant ...` command does not solve the problem. Maybe the permission should be added to the Folio's manifest.

**Comment by adityajoshi12** [comment]
Make sure you have given storage read permission to your app.

**Comment by yashdevelops** [comment]
Did you get a fix to it ? I'm getting the same problem opening up EPUB files ! It opens PDF perfectly.

**Comment by Magby1** [comment]
Yeah, I'm getting the same problem when trying to open from Assets.

**Comment by Magby1** [comment]
> Make sure you have given storage read permission to your app.

Yes i did

**Comment by Nikki-Gunani** [comment]
Did yo guys find any solution ?

**Comment by Magby1** [comment]
No, I eventually Stopped using FolioReader.

**Comment by Nikki-Gunani** [comment]
Are you using any other ePub reader ? Something better than this and is updated ?

**Comment by Magby1** [comment]
No, I had to use Bartesc pdf reader library, If you find an updated one.
Please let me know too!

**Comment by awaisabbasaa11** [comment]
I had the same problem, finally I have solved this issue for more information check this [comment](https://github.com/FolioReader/FolioReader-Android/issues/503#issuecomment-876956247)
