### ISSUE TITLE
opening epub files are stopping the application. I'm new to this and have been stuck here for days. Please please helpp !

### ISSUE THREAD

**Issue by yashdevelops** [FolioReader/FolioReader-Android#468]
Issue / Feature - Issue
FolioReader version - 0.5.4
FolioReader Stock / Modified - Stock
Android SDK - 28
Mobile / Tablet / Emulator Info - Mobile
Crash / Error - Crash

This is how I have declared Folio reader in my AndoridManifest.xml file.

    <activity android:name="com.folioreader.ui.folio.activity.FolioActivity" android:configChanges="orientation|screenSize" android:label="@string/app_name" android:theme="@style/AppTheme.NoActionBar" />

But my Android studio shows a red sign over folio saying,
Class referenced in the manifest, com.folioreader.ui.folio.activity.FolioActivity, was not found in the project or the libraries
Unresolved class 'FolioActivity'

This is how I call Folio Reader :
    
```
                 ```
   if (sdIconStorageDir.toString() != null) {
                        FolioReader folioReader = FolioReader.get();
                        folioReader.setOnHighlightListener(new OnHighlightListener() {
                            @Override
                            public void onHighlight(HighLight highlight, HighLight.HighLightAction type) {
                            }
                        });
                        folioReader.openBook(sdIconStorageDir.toString());
                    }else{
                        Toast.makeText(activity,"This Book not available",Toast.LENGTH_SHORT).show();
                    }
                } catch (Exception e) {
                    Log.e("Exception-down", "" + e.getMessage());
                }
            }
        }
    }

```


Logs from crash :
```
msg: org.greenrobot.eventbus.EventBusException: Subscriber class c.e.d.d.f and its super classes have no public methods with the @Subscribe annotation
stacktrace: org.greenrobot.eventbus.EventBusException: Subscriber class c.e.d.d.f and its super classes have no public methods with the @Subscribe annotation
	at h.a.a.p.a(:5)
	at h.a.a.d.b(Unknown Source:6)
	at c.e.d.d.f.a(Unknown Source:32)
	at androidx.fragment.app.Fragment.b(Unknown Source:20)
	at b.k.a.u.a(:70)
	at b.k.a.u.f(Unknown Source:38)
	at b.k.a.u.a(Unknown Source:46)
	at b.k.a.a.b(Unknown Source:161)
	at b.k.a.u.a(:11)
	at b.k.a.u.c(Unknown Source:88)
	at b.k.a.A.a(:3)
	at com.folioreader.ui.view.DirectionalViewpager.e(:2)
	at com.folioreader.ui.view.DirectionalViewpager.j(Unknown Source:2)
	at com.folioreader.ui.view.DirectionalViewpager.onMeasure(Unknown Source:250)
	at android.view.View.measure(View.java:25090)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(:97)
	at android.view.View.measure(View.java:25090)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6871)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:156)
	at android.view.View.measure(View.java:25090)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6871)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25090)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6871)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25090)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6871)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25090)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6871)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:742)
	at android.view.View.measure(View.java:25090)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3083)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1857)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2146)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7781)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
	at android.view.Choreographer.doFrame(Choreographer.java:726)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7398)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
```

**Comment by ANT000198** [comment]
@yashdevelops ---try adding proguard rule for the eventbus or you can disable it

**Comment by PoyyamozhiRamakrishnan** [comment]
hey @yashdevelops --- try adding proguard rule for event bus or disabling it

**Comment by yashdevelops** [comment]
@PoyyamozhiRamakrishnan Do you have any references from where I can learn or get it ? thank you.

**Comment by PoyyamozhiRamakrishnan** [comment]
@yashdevelops https://github.com/greenrobot/EventBus#r8-proguard, add these proguard rules to your proguard-rules.pro file or change minifyEnabled true to minifyEnabled false in your app build gradle file
