### ISSUE TITLE
Showing errow when going to ContentHighlightActivity?

### ISSUE THREAD

**Issue by akbarasif43** [FolioReader/FolioReader-Android#56]
FAILED BINDER TRANSACTION !!!  (parcel size = 3493604)

`java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 3493604 bytes
                                                                        at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3781)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                     Caused by: android.os.TransactionTooLargeException: data parcel size 3493604 bytes
                                                                        at android.os.BinderProxy.transactNative(Native Method)
                                                                        at android.os.BinderProxy.transact(Binder.java:615)
                                                                        at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3636)
                                                                        at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3773)
                                                                        at android.os.Handler.handleCallback(Handler.java:751) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                        at android.os.Looper.loop(Looper.java:154) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) `

**Comment by mahavir155** [comment]
@akbarasif43 is it possible for you to share epub file?

**Comment by akbarasif43** [comment]
The error is happening only on Android Nougat. After debugging I found that in Nougat when we pass object with intent and if the object is big enough it shows this kind of problem. Here, the library passing entire book object with intent to ContentHighLlight Activity. So inside this activity when it is trying to get the object from intent application is crashing. So I am assuming that to solve this bug may be we need to change the data passing.

**Comment by mahavir155** [comment]
yes, we understood that.. so, we are passing only the objects which is needed in Book class.. Probably it have more resources.. How big is your eBook? any idea on number of chapters? is it audio book?

**Comment by akbarasif43** [comment]
The size of the book is not big. It is only 847KB. Again it has 10 chapters.

**Comment by leon-alan** [comment]
i had the same problem with epubs with many chapters, but not only with the API 24, also with 23 and i solved it but the fix not works with Nougat. Do you found a solution?

**Comment by voipworld** [comment]
hello,
the issue still percist. any solution?

**Comment by voipworld** [comment]
latest git commit still have android.os.TransactionTooLargeException: ... please any help? cant start TOC.
