### ISSUE TITLE
FolioReader-Android NullPointerException at FolioActivity

### ISSUE THREAD

**Issue by premamani125** [FolioReader/FolioReader-Android#80]
As I am new to android programming, I don't now Why I am getting this error. Please help me. 

FATAL EXCEPTION: main
                                                                            Process: myreader.reader.com.myreader, PID: 3034
                                                                            java.lang.NullPointerException
                                                                                at com.folioreader.activity.FolioActivity.configRecyclerViews(FolioActivity.java:229)
                                                                                at com.folioreader.activity.FolioActivity.loadBook(FolioActivity.java:180)
                                                                                at com.folioreader.activity.FolioActivity.access$900(FolioActivity.java:69)
                                                                                at com.folioreader.activity.FolioActivity$3$1.run(FolioActivity.java:169)
                                                                                at android.os.Handler.handleCallback(Handler.java:733)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:146)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5641)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1288)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1104)
                                                                                at dalvik.system.NativeStart.main(Native Method)

**Comment by inlokim** [comment]
Ummm....Who can answer?

**Comment by mahavir155** [comment]
@inlokim @premamani125 with new version 0.3.1, it should be fix.. can you please confirm and close the ticket?

**Comment by Dylc** [comment]
@premamani125 android change it's [permission system since android 6.0 ](https://developer.android.com/guide/topics/permissions/requesting.html#normal-dangerous)

>Dangerous permissions cover areas where the app wants data or resources that involve the user's private information, or could potentially affect the user's stored data or the operation of other apps. For example, the ability to read the user's contacts is a dangerous permission. If an app declares that it needs a dangerous permission, the user has to explicitly grant the permission to the app

and also [here](https://developer.android.com/training/permissions/requesting.html)

>  If the device is running Android 5.1 or lower, or your app's target SDK is 22 or lower: If you list a dangerous permission in your manifest, the user has to grant the permission when they install the app; if they do not grant the permission, the system does not install the app at all.

>    If the device is running Android 6.0 or higher, and your app's target SDK is 23 or higher: The app has to list the permissions in the manifest, and **it must request each dangerous permission it needs while the app is running.** The user can grant or deny each permission, and the app can continue to run with limited capabilities even if the user denies a permission request.


Folio Reader copies files to external storage and this is [dangerous permission](https://developer.android.com/reference/android/Manifest.permission.html#WRITE_EXTERNAL_STORAGE) By the way why copy at all? @mahavir155 
**If user uses android >6.0 you have ask for permission** 

```
// Here, thisActivity is the current activity
if (ContextCompat.checkSelfPermission(thisActivity,
                Manifest.permission.READ_CONTACTS)
        != PackageManager.PERMISSION_GRANTED) {

    // Should we show an explanation?
    if (ActivityCompat.shouldShowRequestPermissionRationale(thisActivity,
            Manifest.permission.READ_CONTACTS)) {

        // Show an explanation to the user *asynchronously* -- don't block
        // this thread waiting for the user's response! After the user
        // sees the explanation, try again to request the permission.

    } else {

        // No explanation needed, we can request the permission.

        ActivityCompat.requestPermissions(thisActivity,
                new String[]{Manifest.permission.READ_CONTACTS},
                MY_PERMISSIONS_REQUEST_READ_CONTACTS);

        // MY_PERMISSIONS_REQUEST_READ_CONTACTS is an
        // app-defined int constant. The callback method gets the
        // result of the request.
    }
}
```

you will get result in [callback](https://developer.android.com/reference/android/support/v4/app/ActivityCompat.OnRequestPermissionsResultCallback.html)

**Comment by mahavir155** [comment]
@Dylc r2-streamer library starts the light weight server and it uses epub file path as a servers base route..
