### ISSUE TITLE
App crashes when spin reference is less than table of content 

### ISSUE THREAD

**Issue by umerk44** [FolioReader/FolioReader-Android#86]
>  FATAL EXCEPTION: main
>                                                                                 Process: com.folioreader.android.sample, PID: 23355
>                                                                                 java.lang.IndexOutOfBoundsException: Invalid index 13, size is 5
>                                                                                     at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
>                                                                                     at java.util.ArrayList.get(ArrayList.java:308)
>                                                                                     at com.folioreader.fragments.ContentsFragment$TOCAdapter$1.onClick(ContentsFragment.java:147)
>                                                                                     at android.view.View.performClick(View.java:4780)
>                                                                                     at android.view.View$PerformClick.run(View.java:19866)
>                                                                                     at android.os.Handler.handleCallback(Handler.java:739)
>                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                                                     at android.os.Looper.loop(Looper.java:135)
>                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5254)
>                                                                                     at java.lang.reflect.Method.invoke(Native Method)
>                                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
>                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
>                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

I notice some times spin reference are less the table of content and when user select table of content it's crashes with index out of bound exception. So wondering how spin reference calculation really happening here.

**Comment by mahavir155** [comment]
@umerk44 please check if this issue is there on new version 0.3.1
