### ISSUE TITLE
NoclassdefFound Error

### ISSUE THREAD

**Issue by sinshm** [FolioReader/FolioReader-Android#89]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       java.lang.NoClassDefFoundError: android/webkit/JavascriptInterface
                                                                           at java.lang.reflect.Method.isAnnotationPresent(Native Method)
                                                                           at java.lang.reflect.Method.isAnnotationPresent(Method.java:284)
                                                                           at com.squareup.otto.AnnotatedHandlerFinder.loadAnnotatedMethods(AnnotatedHandlerFinder.java:72)
                                                                           at com.squareup.otto.AnnotatedHandlerFinder.loadAnnotatedProducerMethods(AnnotatedHandlerFinder.java:49)

**Comment by mahavir155** [comment]
@sinshm please check with latest version 0.3.1
